#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

# Positive generation: Java.
run_expect_status 0 "$CLI" generate bindings --lang java "$SPEC" --out "$TMPDIR/out-java"
assert_output_contains "generated $TMPDIR/out-java/common/com/statespec/backend/Backend.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Json.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Backend.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/ExternalSystem.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/FeatureFlag.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Lease.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Log.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Metric.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Queue.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Workflow.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryBackend.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryTransaction.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/Codec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/QueueCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LeaseCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/WorkflowCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/ObservabilityCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/QueueStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LeaseStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/WorkflowStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogSink.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricSink.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcDescriptors.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRepository.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcWorkers.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java"
assert_file_exists "$TMPDIR/out-java/Makefile"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiCodecs.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiServer.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiRoutes.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ExternalSystemOperatorMetadataApi.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerDescriptors.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerContexts.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRegistry.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerApplication.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerQueues.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerLeases.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerWorkflows.java"
assert_file_contains "$TMPDIR/out-java/Makefile" "JAVAC ?= javac"
assert_file_contains "$TMPDIR/out-java/Makefile" "help:"
assert_file_contains "$TMPDIR/out-java/Makefile" "Default target: all -> check -> build"
assert_file_contains "$TMPDIR/out-java/Makefile" "BUILD_DIR ?= build/classes"
assert_file_contains "$TMPDIR/out-java/Makefile" "COMMON_SOURCES :="
assert_file_contains "$TMPDIR/out-java/Makefile" "API_SOURCES :="
assert_file_contains "$TMPDIR/out-java/Makefile" "WORKER_SOURCES :="
assert_file_contains "$TMPDIR/out-java/Makefile" "COMMON_EXTENSION_SOURCES :="
assert_file_contains "$TMPDIR/out-java/Makefile" "API_EXTENSION_SOURCES :="
assert_file_contains "$TMPDIR/out-java/Makefile" "WORKER_EXTENSION_SOURCES :="
assert_file_not_contains "$TMPDIR/out-java/Makefile" "find . -name '*.java'"
assert_file_contains "$TMPDIR/out-java/Makefile" "\$(JAVAC) -d \$(BUILD_DIR) \$(COMMON_SOURCES)"
assert_file_contains "$TMPDIR/out-java/Makefile" "\$(COMMON_EXTENSION_SOURCES) \$(API_SOURCES) \$(API_EXTENSION_SOURCES)"
assert_file_contains "$TMPDIR/out-java/Makefile" "\$(COMMON_EXTENSION_SOURCES) \$(WORKER_SOURCES) \$(WORKER_EXTENSION_SOURCES)"
assert_file_contains "$TMPDIR/out-java/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-java/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-java/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-java/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java" "class ApiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java" "apiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiCodecs.java" "decodeStartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiCodecs.java" "encodeStartOrderProcessingResponse"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "class ApiHandlers"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "interface Handler"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "handleStartOrderProcessing"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlerRegistry.java" "decodeStartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlerRegistry.java" "encodeStartOrderProcessingResponse"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlerRegistry.java" "handler_not_implemented"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java" "findApiRoute"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java" "dispatchApiRoute"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java" "dispatchApiOperationRoute"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiServer.java" "class ApiServer"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiServer.java" "findApiServer"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiRoutes.java" "apiRouteDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ExternalSystemOperatorMetadataApi.java" "ExternalSystemOperatorMetadataHandler"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "private final Backend backend"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "backend.memory"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public final class ApiProcess"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized void bootstrap()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public void requestStop()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "private Thread thread"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "AtomicBoolean stopRequested"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized void start()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public int join()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized boolean isRunning()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "boolean entityGcEnabled"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "interface EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized void addEntityGcWorker"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "startEntityGcWorkers()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "interface ApiTransport"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "return server.handle(routeName, context)"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "final class LocalBlocking"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "int run() throws InterruptedException"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "void requestStop()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "stopRequested.await()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "transport.requestStop()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "backend.memory.InMemoryBackend"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "new ApiTransport.LocalBlocking()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "ApiProcess.Config.allServers"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "addShutdownHook"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "process.start()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "process.join()"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "ApiApplication.createDefault"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerDescriptors.java" "class WorkerDescriptors"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerContexts.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRegistry.java" "findWorkerDescriptor"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerApplication.java" "class WorkerApplication"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "class WorkerProcess"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "static final class Config"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public synchronized void start()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public int join()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public synchronized boolean isRunning()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public void requestStop()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "startWorkerLoops"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "interface Handler"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "DefaultHandler implements Handler"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "handleOrderProcessingValidateOrder"
assert_file_not_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "handleWorkflowStep"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "workflowStepHandlerKeys"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java" "class WorkflowRunner"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java" "handleOrderProcessingValidateOrder"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java" "keepAliveStep"
assert_file_not_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerHandlers.java"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "runOnce"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "private final Backend backend"
assert_file_not_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "backend.memory"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "record Config(boolean entityGcEnabled"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "interface EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "startEntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "public void requestStop()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "WorkflowStepHandlers.DefaultHandler"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "WorkerProcess"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "addShutdownHook"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "process.start()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "process.join()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "backend.memory.InMemoryBackend"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerQueues.java" "queueDefinitions"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerLeases.java" "leaseDefinitions"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerWorkflows.java" "workflowDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Backend.java" "enum FieldType"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Backend.java" "FieldType type"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Backend.java" "String typeName"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Workflow.java" "record KeepAliveWorkflowStepRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Workflow.java" "keepAliveStepTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryBackend.java" "public final class InMemoryBackend"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryTransaction.java" "public final class InMemoryTransaction"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/Codec.java" "final class Codec"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagCodec.java" "featureFlagDefinitionToJson"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogCodec.java" "logDefinitionToJson"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricCodec.java" "metricDefinitionToJson"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagStore.java" "implements FeatureFlag"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/QueueStore.java" "implements Queue"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/LeaseStore.java" "implements Lease"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/WorkflowStore.java" "implements Workflow"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogSink.java" "inspectEvents"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricSink.java" "inspectSamples"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcDescriptors.java" "record Descriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcDescriptors.java" "Descriptors.ORDER_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcDescriptors.java" "Descriptors.ORDER_STATUS_FAILED"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRepository.java" "interface EntityGcRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcWorkers.java" "final class EntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "class Descriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ShapeDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "String tenant_id"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ValueDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EnumDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EventDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EventEnvelope"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "buildOrderAcceptedEvent"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemMetadataMappingDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "missingExternalSystemMetadataMappingSources"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "sourceValue"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "DefaultExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "DefaultExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ExternalSystemClient"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "buildExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "callExternalSystem"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "externalSystemMetadataKey"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "externalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "Optional<String> tenantField"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "List<String> keyFields"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "Optional.of(\"tenant_id\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"metadata.base_url\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"client.base_url\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/ExternalSystem.java" "interface ExternalSystem"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "externalSystemMetadataLookup"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "resolveExternalSystemMetadataTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "keyComplete()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiRequestContext"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiResponse"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ApiHandler"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "apiDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"OrderApi\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "List.of(\"StartOrderProcessing\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"OrderApi.StartOrderProcessing\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record WorkerDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record WorkerContext"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface Worker"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"OrderWorker\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "Optional.of(\"EmailDispatch.SendConfirmation\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record PolicyDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record EntityInvariantDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface EntityRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "class DefaultEntityRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface AccountRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "class DefaultAccountRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface OrderRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "class DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "ACCOUNT_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "ORDER_FIELD_TENANT_ID"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "ORDER_INDEX_BY_TENANT_STATUS"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "new FieldDescriptor(ORDER_FIELD_TENANT_ID"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "return listByIndexTx(tx, ORDER_INDEX_BY_TENANT_STATUS"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "createTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "listByIndexTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "listByTenantStatusTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "listByTenantOrderTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "entityLookupFromDocument"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "entityDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "featureFlagDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "shapeDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "valueDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "enumDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "eventDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "externalSystemDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "apiDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "apiServerDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workerDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "policyDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "queueDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "leaseDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workflowDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "EmailDispatch"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderReconciler"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "2L"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "validate_order"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "NewScheduler"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderAmount"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderStatus"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderAccepted"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "Stripe"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "Optional.of(\"/v1/tenants/{tenantId}/orders/{order_id}/start\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderAccess"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record LogDefinition"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "logDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workflow.launch.decision"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record MetricDefinition"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "metricDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "ensureSystemCollections"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerFeatureFlagDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerQueueDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerLeaseDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerRuntimeCatalogTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerRuntimeCatalog("
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "bootstrapRuntimeCatalog("
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "new IndexDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerObservabilityCatalogTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "registerWorkflowDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "void bootstrap()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "void bootstrap()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workflow_launch_attempts_total"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "Optional.of(\"composition\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "new EntityInvariantDescriptor(\"valid_status\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "ORDER_INDEX_BY_TENANT_STATUS"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "ORDER_INDEX_BY_TENANT_ORDER"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "new GarbageCollectionPolicy(\"P30D\", \"tombstone\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "FieldType.STRING"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "FieldType.NAMED"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "FieldType.TIMESTAMP"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "FieldType.OPTIONAL"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"OrderStatus\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "\"int?\""

cp "$SCRIPT_DIR/MetadataResolverFixture.java" "$TMPDIR/out-java/common/com/statespec/generated/MetadataResolverFixture.java"
cp "$SCRIPT_DIR/MemoryBackendFixture.java" "$TMPDIR/out-java/common/com/statespec/backend/memory/MemoryBackendFixture.java"
(cd "$TMPDIR/out-java" && make check)
${JAVA:-java} -cp "$TMPDIR/out-java/build/classes" com.statespec.generated.MetadataResolverFixture
${JAVA:-java} -cp "$TMPDIR/out-java/build/classes" com.statespec.backend.memory.MemoryBackendFixture
