#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

# Positive generation: Java.
run_expect_status 0 "$CLI" generate bindings --lang java "$SPEC" --out "$TMPDIR/out-java"
assert_output_contains "generated $TMPDIR/out-java/common/com/statespec/backend/Backend.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Json.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Backend.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/ExternalSystem.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/FeatureFlag.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Lease.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Log.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Metric.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Queue.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/Workflow.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryBackend.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryTransaction.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/Codec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/QueueCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LeaseCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/WorkflowCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/ObservabilityCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricCodec.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/QueueStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LeaseStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/WorkflowStore.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogSink.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricSink.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcTypes.java"
assert_file_not_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcDescriptors.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRepository.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcWorkers.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Gc.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ApiDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ApiRouteDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ApiServerDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/WorkerDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/WorkerContext.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EntityDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ExternalSystemDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ShapeDescriptor.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/FeatureFlagDefinition.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/shapes/StartOrderProcessingRequest.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/shapes/ShapeCatalog.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/CoreDescriptorModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ShapeDescriptorModule.java"
assert_file_not_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/shapes/StartOrderProcessingRequestDescriptorModule.java"
assert_file_not_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ApiDescriptorModule.java"
assert_file_not_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/WorkerDescriptorModule.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/Catalog.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/OrderWorkerDescriptorModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeDescriptorModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeFeatureFlagRegistrationModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeQueueRegistrationModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeLeaseRegistrationModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeWorkflowRegistrationModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeObservabilityRegistrationModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/DescriptorCatalog.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/DefaultEntityRepository.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityCreateRequest.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityDeleteRequest.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityGetRequest.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityKeyValue.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityListByIndexRequest.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityLookup.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityRepository.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityUpsertRequest.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java"
assert_file_not_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/entities/AccountDescriptorModule.java"
assert_file_not_exists "$TMPDIR/out-java/common/com/statespec/generated/descriptors/entities/OrderDescriptorModule.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Model.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Persistence.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Schema.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Model.java" "ACCOUNT_ENTITY_NAME = \"Account\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_INDEX_BY_TENANT_STATUS = \"by_tenant_status\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "orderFieldDescriptors()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "orderIndexDescriptors()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_RELATION_ACCOUNT_ID_TARGET = \"Account\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "ORDER_SCHEMA_VERSION = 1L"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "ORDER_OWNERSHIP_LIFECYCLE = \"authoritative\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "ORDER_STATE_FAILED_GC_AFTER = \"P30D\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "orderCollectionDescriptor()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "interface OrderRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "class DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "listByTenantStatusTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "buildOrderLookup"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "import com.statespec.generated.descriptors.CoreDescriptorModule;"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "import com.statespec.generated.descriptors.entities.AccountDescriptorModule;"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "import com.statespec.generated.descriptors.entities.OrderDescriptorModule;"
assert_file_exists "$TMPDIR/out-java/Makefile"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/descriptors/Catalog.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/descriptors/StartOrderProcessingDescriptorModule.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiCodecs.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiServer.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiRoutes.java"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/ExternalSystemOperatorMetadataApi.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerDescriptors.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerContexts.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRegistry.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerApplication.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerQueues.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerLeases.java"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerWorkflows.java"
assert_file_contains "$TMPDIR/out-java/Makefile" "JAVAC ?= javac"
assert_file_contains "$TMPDIR/out-java/Makefile" "help:"
assert_file_contains "$TMPDIR/out-java/Makefile" "Default target: all -> check -> build"
assert_file_contains "$TMPDIR/out-java/Makefile" "BUILD_DIR ?= build/classes"
assert_file_contains "$TMPDIR/out-java/Makefile" "COMMON_SOURCES := \$(shell find common -name '*.java' -print)"
assert_file_contains "$TMPDIR/out-java/Makefile" "API_SOURCES := \$(shell if [ -d api ]; then find api -name '*.java' -print; fi)"
assert_file_contains "$TMPDIR/out-java/Makefile" "WORKER_SOURCES := \$(shell if [ -d worker ]; then find worker -name '*.java' -print; fi)"
assert_file_not_contains "$TMPDIR/out-java/Makefile" "common/com/statespec/generated/descriptors/CoreDescriptorModule.java"
assert_file_not_contains "$TMPDIR/out-java/Makefile" "common/com/statespec/generated/descriptors/entities/AccountDescriptorModule.java"
assert_file_not_contains "$TMPDIR/out-java/Makefile" "COMMON_EXTENSION_SOURCES :="
assert_file_not_contains "$TMPDIR/out-java/Makefile" "API_EXTENSION_SOURCES :="
assert_file_not_contains "$TMPDIR/out-java/Makefile" "WORKER_EXTENSION_SOURCES :="
assert_file_contains "$TMPDIR/out-java/Makefile" "\$(JAVAC) -d \$(BUILD_DIR) \$(COMMON_SOURCES)"
assert_file_contains "$TMPDIR/out-java/Makefile" "\$(JAVAC) -d \$(BUILD_DIR) \$(COMMON_SOURCES) \$(API_SOURCES)"
assert_file_contains "$TMPDIR/out-java/Makefile" "\$(JAVAC) -d \$(BUILD_DIR) \$(COMMON_SOURCES) \$(WORKER_SOURCES)"
assert_file_contains "$TMPDIR/out-java/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-java/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-java/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-java/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java" "class ApiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java" "apiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDescriptors.java" "Catalog.apiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/Catalog.java" "StartOrderProcessingDescriptorModule.apiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/Catalog.java" "StartOrderProcessingDescriptorModule.apiRouteDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/StartOrderProcessingDescriptorModule.java" "apiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/StartOrderProcessingDescriptorModule.java" "apiRouteDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/codecs/ApiCodecsStartOrderProcessingRequest.java" "decodeStartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/codecs/ApiCodecsStartOrderProcessingResponse.java" "encodeStartOrderProcessingResponse"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "class ApiHandlers"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "interface Handler"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "handleStartOrderProcessing"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlers.java" "interface BusinessHandler"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlerRegistry.java" "businessHandler.handleStartOrderProcessing"
assert_file_not_exists "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlerRegistryOrder.java"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiHandlerRegistry.java" "handler_not_implemented"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java" "findApiRoute"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java" "dispatchApiRoute"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiDispatcher.java" "dispatchApiOperationRoute"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiServer.java" "class ApiServer"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiServer.java" "findApiServer"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiRoutes.java" "apiRouteDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ExternalSystemOperatorMetadataApi.java" "ExternalSystemOperatorMetadataHandler"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "private final Backend backend"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "backend.memory"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public final class ApiProcess"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized void bootstrap()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public void requestStop()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "private Thread thread"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "AtomicBoolean stopRequested"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized void start()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public int join()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized boolean isRunning()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "boolean entityGcEnabled"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "interface EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "public synchronized void addEntityGcWorker"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "startEntityGcWorkers()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "interface ApiTransport"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "return server.handle(routeName, context)"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "final class LocalBlocking"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "int run() throws InterruptedException"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "void requestStop()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiTransport.java" "stopRequested.await()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiProcess.java" "transport.requestStop()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "backend.memory.InMemoryBackend"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "backend.runtime.EntityGcRegistration"
assert_file_exists "$TMPDIR/out-java/api/com/statespec/generated/EntityGcCatalog.java"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "new ApiTransport.LocalBlocking()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "ApiProcess.Config.allServers"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "EntityGcRegistration.registerEntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "EntityGcCatalog.descriptors()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "process.addEntityGcWorker"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "addShutdownHook"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "process.start()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/EntityGcCatalog.java" "List<EntityGcTypes.Descriptor>"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/EntityGcCatalog.java" "entities.order.Gc.descriptor()"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "process.join()"
assert_file_not_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiMain.java" "ApiApplication.createDefault"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerEntityGcCatalog.java"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerDescriptors.java" "class WorkerDescriptors"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerContexts.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRegistry.java" "findWorkerDescriptor"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerApplication.java" "class WorkerApplication"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "class WorkerProcess"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "static final class Config"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public synchronized void start()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public int join()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public synchronized boolean isRunning()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "public void requestStop()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerProcess.java" "startWorkerLoops"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "interface Handler"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "DefaultHandler implements Handler"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "handleOrderProcessingValidateOrder"
assert_file_not_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "handleWorkflowStep"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowStepHandlers.java" "workflowStepHandlerKeys"
assert_file_exists "$TMPDIR/out-java/worker/com/statespec/generated/workflows/OrderProcessingWorkerModule.java"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/workflows/OrderProcessingWorkerModule.java" "handleOrderProcessingValidateOrder"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java" "class WorkflowRunner"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java" "OrderProcessingWorkerModule.dispatchStep"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkflowRunner.java" "keepAliveStep"
assert_file_not_exists "$TMPDIR/out-java/worker/com/statespec/generated/WorkerHandlers.java"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "runOnce"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "private final Backend backend"
assert_file_not_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "backend.memory"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "record Config(boolean entityGcEnabled"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "interface EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "startEntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "public void requestStop()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "WorkflowStepHandlers.DefaultHandler"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "WorkerProcess"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "EntityGcRegistration.registerEntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "WorkerEntityGcCatalog.descriptors()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "runtime.addEntityGcWorker"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerEntityGcCatalog.java" "List<EntityGcTypes.Descriptor>"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerEntityGcCatalog.java" "entities.order.Gc.descriptor()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "addShutdownHook"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "process.start()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "process.join()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "backend.memory.InMemoryBackend"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerMain.java" "backend.runtime.EntityGcRegistration"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerQueues.java" "queueDefinitions"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerLeases.java" "leaseDefinitions"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerWorkflows.java" "workflowDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Backend.java" "enum FieldType"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Backend.java" "FieldType type"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Backend.java" "String typeName"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Workflow.java" "record KeepAliveWorkflowStepRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/Workflow.java" "keepAliveStepTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryBackend.java" "public final class InMemoryBackend"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/memory/InMemoryTransaction.java" "public final class InMemoryTransaction"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/Codec.java" "final class Codec"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagCodec.java" "featureFlagDefinitionToJson"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogCodec.java" "logDefinitionToJson"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricCodec.java" "metricDefinitionToJson"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/FeatureFlagStore.java" "implements FeatureFlag"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/QueueStore.java" "implements Queue"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/LeaseStore.java" "implements Lease"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/WorkflowStore.java" "implements Workflow"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/LogSink.java" "inspectEvents"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/MetricSink.java" "inspectSamples"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcTypes.java" "record Descriptor"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcTypes.java" "Gc.descriptor()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Gc.java" "public static EntityGcTypes.Descriptor descriptor()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Gc.java" "Model.ORDER_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Gc.java" "Model.ORDER_STATUS_FAILED"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Gc.java" "Schema.ORDER_STATE_FAILED_GC_AFTER"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRepository.java" "interface EntityGcRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcWorkers.java" "final class EntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "class DefaultEntityGcRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "registerEntityGcWorkers"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "List<EntityGcTypes.Descriptor> descriptors"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "List.of()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "for (var descriptor : descriptors)"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "Scheduler"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "Lease"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "Queue"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "Workflow"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "FeatureFlag"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "Log"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/backend/runtime/EntityGcRegistration.java" "Metric"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "class Descriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/DescriptorCatalog.java" "package com.statespec.generated.descriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/DescriptorCatalog.java" "final class DescriptorCatalog"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityRepository.java" "package com.statespec.generated.entities"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityRepository.java" "interface EntityRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityKeyValue.java" "record EntityKeyValue"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityLookup.java" "record EntityLookup"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/DefaultEntityRepository.java" "class DefaultEntityRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "package com.statespec.generated.runtime"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "final class RuntimeRegistration"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record FeatureFlagDefinition"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ShapeDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/FeatureFlagDefinition.java" "record FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ShapeDescriptor.java" "record ShapeDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ShapeDescriptorModule.java" "shapeDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/shapes/ShapeCatalog.java" "shapeDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/shapes/StartOrderProcessingRequest.java" "record StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/shapes/StartOrderProcessingRequest.java" "String tenant_id"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ValueDescriptor.java" "record ValueDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EnumDescriptor.java" "record EnumDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EventDescriptor.java" "record EventDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EventEnvelope.java" "record EventEnvelope"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "buildOrderAcceptedEvent"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/EventDescriptorModule.java" "buildOrderAcceptedEvent"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ExternalSystemDescriptor.java" "record ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ExternalSystemMetadataDescriptor.java" "record ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ExternalSystemMetadataMappingDescriptor.java" "record ExternalSystemMetadataMappingDescriptor"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemMetadataMappingPlan"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ExternalSystemOperatorMetadataUpsertRequest"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadataMappingPlan.java" "record ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemOperatorMetadataUpsertRequest.java" "record ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemOperatorMetadataRepository.java" "interface ExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadataMappingInputs.java" "record ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadataMissingMappingSource.java" "record ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "missingExternalSystemMetadataMappingSources"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadataMappingInputs.java" "sourceValue"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadataMappingApplicator.java" "interface ExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/DefaultExternalSystemMetadataMappingApplicator.java" "DefaultExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/DefaultExternalSystemOperatorMetadataRepository.java" "DefaultExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemClient.java" "interface ExternalSystemClient"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemCallRequest.java" "record ExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "buildExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "callExternalSystem"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "externalSystemMetadataKey"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "externalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ExternalSystemMetadataDescriptor.java" "Optional<String> tenantField"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ExternalSystemMetadataDescriptor.java" "List<String> keyFields"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ExternalSystemDescriptorModule.java" "Optional.of(\"tenant_id\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ExternalSystemDescriptorModule.java" "\"metadata.base_url\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ExternalSystemDescriptorModule.java" "\"client.base_url\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/backend/ExternalSystem.java" "interface ExternalSystem"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "externalSystemMetadataLookup"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "resolveExternalSystemMetadataTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemMetadata.java" "keyComplete()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ApiDescriptor.java" "record ApiDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ApiServerDescriptor.java" "record ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/ApiRouteDescriptor.java" "record ApiRouteDescriptor"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiRequestContext"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "record ApiResponse"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/ApiRequestContext.java" "record ApiRequestContext"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/ApiResponse.java" "record ApiResponse"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ApiHandler"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/external/metadata/ExternalSystemOperatorMetadataApiHandler.java" "interface ExternalSystemOperatorMetadataApiHandler"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "apiDescriptors"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/Catalog.java" "\"OrderApi\""
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/Catalog.java" "List.of(\"StartOrderProcessing\")"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/StartOrderProcessingDescriptorModule.java" "\"OrderApi.StartOrderProcessing\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/WorkerDescriptor.java" "record WorkerDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/WorkerContext.java" "record WorkerContext"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface Worker"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workerDescriptors"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/Catalog.java" "workerDescriptors"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/Catalog.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/OrderWorkerDescriptorModule.java" "\"OrderWorker\""
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/OrderWorkerDescriptorModule.java" "Optional.of(\"EmailDispatch.SendConfirmation\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/PolicyDescriptor.java" "record PolicyDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/GarbageCollectionPolicy.java" "record GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EntityStateDescriptor.java" "record EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EntityOwnershipDescriptor.java" "record EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EntityRelationDescriptor.java" "record EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EntityChildDescriptor.java" "record EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/EntityInvariantDescriptor.java" "record EntityInvariantDescriptor"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "interface EntityRepository"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "class DefaultEntityRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Persistence.java" "interface AccountRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Persistence.java" "class DefaultAccountRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "interface OrderRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "class DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/account/Model.java" "ACCOUNT_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_FIELD_TENANT_ID"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_INDEX_BY_TENANT_STATUS"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_INDEX_BY_TENANT_ORDER"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_FIELD_TENANT_ID"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "orderCollectionDescriptor()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "buildOrderLookup"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "listByTenantStatusTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Persistence.java" "listByTenantOrderTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/EntityRepository.java" "entityLookupFromDocument"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "entityDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "featureFlagDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "shapeDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "valueDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "enumDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "eventDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "externalSystemDescriptors"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "apiDescriptors"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "apiServerDescriptors"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workerDescriptors"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/Catalog.java" "workerDescriptors"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/worker/descriptors/Catalog.java" "workerContexts"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "policyDescriptors"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "queueDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "leaseDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workflowDefinitions"
assert_file_exists "$TMPDIR/out-java/common/com/statespec/generated/workflows/OrderProcessingDescriptorModule.java"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "EmailDispatch"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderReconciler"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/workflows/OrderProcessingDescriptorModule.java" "2L"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/workflows/OrderProcessingDescriptorModule.java" "validate_order"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "NewScheduler"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/shapes/ShapeCatalog.java" "START_ORDER_PROCESSING_REQUEST_SHAPE_NAME"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderAmount"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderStatus"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderAccepted"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/ExternalSystemDescriptorModule.java" "Stripe"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/StartOrderProcessingDescriptorModule.java" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/descriptors/StartOrderProcessingDescriptorModule.java" "Optional.of(\"/v1/tenants/{tenantId}/orders/{order_id}/start\")"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "OrderAccess"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/LogDefinition.java" "record LogDefinition"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "logDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workflow.launch.decision"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/types/MetricDefinition.java" "record MetricDefinition"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "metricDefinitions"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "ensureSystemCollections"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "com.statespec.generated.entities.order.Schema.orderCollectionDescriptor()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerFeatureFlagDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerQueueDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerLeaseDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeFeatureFlagRegistrationModule.java" "registerFeatureFlagDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeQueueRegistrationModule.java" "registerQueueDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeLeaseRegistrationModule.java" "registerLeaseDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerRuntimeCatalogTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerRuntimeCatalog("
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "bootstrapRuntimeCatalog("
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "new CollectionDescriptor"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerObservabilityCatalogTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/runtime/RuntimeRegistration.java" "registerWorkflowDefinitionsTx"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "bootstrapRuntimeCatalog("
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "logLevelFromDescriptor"
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "metricKindFromDescriptor"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "RuntimeRegistration.bootstrapRuntimeCatalog"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "RuntimeRegistration.bootstrapRuntimeCatalog"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeObservabilityRegistrationModule.java" "registerObservabilityCatalogTx"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/descriptors/RuntimeWorkflowRegistrationModule.java" "registerWorkflowDefinitionsTx"
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/ApiApplication.java" "void bootstrap()"
assert_file_contains "$TMPDIR/out-java/worker/com/statespec/generated/WorkerRuntime.java" "void bootstrap()"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "workflow_launch_attempts_total"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_RELATION_ACCOUNT_ID_RELATION_KIND = \"composition\""
assert_file_not_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "new EntityInvariantDescriptor(\"valid_status\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_INDEX_BY_TENANT_STATUS"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_INDEX_BY_TENANT_ORDER"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "ORDER_STATE_FAILED_GC_AFTER = \"P30D\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Schema.java" "ORDER_STATE_FAILED_GC_MODE = \"tombstone\""
assert_file_contains "$TMPDIR/out-java/api/com/statespec/generated/shapes/ShapeCatalog.java" "FieldType.STRING"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/Descriptors.java" "FieldType.NAMED"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "FieldType.TIMESTAMP"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "FieldType.OPTIONAL"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_FIELD_STATUS_TYPE_NAME = \"string\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_FIELD_RETRY_COUNT_TYPE_NAME = \"int?\""
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_FIELD_STATUS, FieldType.STRING, ORDER_FIELD_STATUS_TYPE_NAME"
assert_file_contains "$TMPDIR/out-java/common/com/statespec/generated/entities/order/Model.java" "ORDER_FIELD_RETRY_COUNT, FieldType.OPTIONAL, ORDER_FIELD_RETRY_COUNT_TYPE_NAME"

cp "$SCRIPT_DIR/MetadataResolverFixture.java" "$TMPDIR/out-java/common/com/statespec/generated/MetadataResolverFixture.java"
cp "$SCRIPT_DIR/MemoryBackendFixture.java" "$TMPDIR/out-java/common/com/statespec/backend/memory/MemoryBackendFixture.java"
(cd "$TMPDIR/out-java" && make check)
${JAVA:-java} -cp "$TMPDIR/out-java/build/classes" com.statespec.generated.MetadataResolverFixture
${JAVA:-java} -cp "$TMPDIR/out-java/build/classes" com.statespec.backend.memory.MemoryBackendFixture
