#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

run_expect_status 0 "$CLI" generate bindings --lang go "$SPEC" --out "$TMPDIR/out-go"
assert_output_contains "generated $TMPDIR/out-go/common/backend/backend.go"
assert_file_exists "$TMPDIR/out-go/common/backend/json.go"
assert_file_exists "$TMPDIR/out-go/common/backend/backend.go"
assert_file_exists "$TMPDIR/out-go/common/backend/external_system.go"
assert_file_exists "$TMPDIR/out-go/common/backend/feature_flag.go"
assert_file_exists "$TMPDIR/out-go/common/backend/lease.go"
assert_file_exists "$TMPDIR/out-go/common/backend/log.go"
assert_file_exists "$TMPDIR/out-go/common/backend/metric.go"
assert_file_exists "$TMPDIR/out-go/common/backend/queue.go"
assert_file_exists "$TMPDIR/out-go/common/backend/workflow.go"
assert_file_exists "$TMPDIR/out-go/common/backend/memory/backend.go"
assert_file_exists "$TMPDIR/out-go/common/backend/memory/transaction.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_feature_flags.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_queues.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_leases.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_workflows.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_observability.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_logs.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/codec_metrics.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/feature_flags.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/queues.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/leases.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/workflows.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/logs.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/metrics.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/entity_gc_descriptors.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/entity_gc_repository.go"
assert_file_exists "$TMPDIR/out-go/common/backend/runtime/entity_gc_workers.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors.go"
assert_file_exists "$TMPDIR/out-go/common/backend/shape_descriptors.go"
assert_file_exists "$TMPDIR/out-go/common/backend/start_order_processing_request_shape_descriptors.go"
assert_file_exists "$TMPDIR/out-go/common/backend/shapes/start_order_processing_request.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/core.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/shapes.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/apis.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/workers.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/runtime.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/entities/account.go"
assert_file_exists "$TMPDIR/out-go/common/backend/descriptors/entities/order.go"
assert_file_exists "$TMPDIR/out-go/common/backend/account_descriptors.go"
assert_file_exists "$TMPDIR/out-go/common/backend/order_descriptors.go"
assert_file_exists "$TMPDIR/out-go/common/entities/account/model.go"
assert_file_exists "$TMPDIR/out-go/common/entities/account/persistence.go"
assert_file_exists "$TMPDIR/out-go/common/entities/account/schema.go"
assert_file_exists "$TMPDIR/out-go/common/entities/order/model.go"
assert_file_exists "$TMPDIR/out-go/common/entities/order/persistence.go"
assert_file_exists "$TMPDIR/out-go/common/entities/order/schema.go"
assert_file_contains "$TMPDIR/out-go/common/entities/account/model.go" "AccountEntityName = \"Account\""
assert_file_contains "$TMPDIR/out-go/common/entities/order/model.go" "OrderIndexByTenantStatus = \"by_tenant_status\""
assert_file_contains "$TMPDIR/out-go/common/entities/order/model.go" "func OrderFieldDescriptors() []backend.FieldDescriptor"
assert_file_contains "$TMPDIR/out-go/common/entities/order/model.go" "func OrderIndexDescriptors() []backend.IndexDescriptor"
assert_file_contains "$TMPDIR/out-go/common/entities/order/model.go" "OrderRelationAccountIdTarget = \"Account\""
assert_file_contains "$TMPDIR/out-go/common/entities/order/schema.go" "OrderSchemaVersion uint64 = 1"
assert_file_contains "$TMPDIR/out-go/common/entities/order/schema.go" "OrderOwnershipLifecycle = \"authoritative\""
assert_file_contains "$TMPDIR/out-go/common/entities/order/schema.go" "OrderStateFailedGcAfter = \"P30D\""
assert_file_contains "$TMPDIR/out-go/common/entities/order/schema.go" "func OrderCollectionDescriptor() backend.CollectionDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "_ \"statespec-generated/common/backend/descriptors\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "_ \"statespec-generated/common/backend/descriptors/entities\""
assert_file_contains "$TMPDIR/out-go/common/backend/account_descriptors.go" "const ("
assert_file_contains "$TMPDIR/out-go/common/backend/account_descriptors.go" "AccountEntityDescriptors"
assert_file_contains "$TMPDIR/out-go/common/backend/account_descriptors.go" "type DefaultAccountRepository struct{}"
assert_file_not_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type DefaultAccountRepository struct{}"
assert_file_exists "$TMPDIR/out-go/go.mod"
assert_file_exists "$TMPDIR/out-go/Makefile"
assert_file_exists "$TMPDIR/out-go/api/backend/api_descriptors.go"
assert_file_exists "$TMPDIR/out-go/api/backend/descriptors/start_order_processing.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_codecs.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_handlers.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_dispatcher.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_process.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_server.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_transport.go"
assert_file_exists "$TMPDIR/out-go/api/backend/api_routes.go"
assert_file_exists "$TMPDIR/out-go/api/backend/external_system_operator_metadata_api.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_descriptors.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_contexts.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_registry.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_application.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_process.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/workflow_step_handlers.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/workflow_runner.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_queues.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_leases.go"
assert_file_exists "$TMPDIR/out-go/worker/backend/worker_workflows.go"
assert_file_contains "$TMPDIR/out-go/go.mod" "module statespec-generated"
assert_file_contains "$TMPDIR/out-go/go.mod" "go 1.22"
assert_file_contains "$TMPDIR/out-go/Makefile" "GO ?= go"
assert_file_contains "$TMPDIR/out-go/Makefile" "BIN_DIR ?= build/bin"
assert_file_contains "$TMPDIR/out-go/Makefile" "help:"
assert_file_contains "$TMPDIR/out-go/Makefile" "Default target: all -> check"
assert_file_contains "$TMPDIR/out-go/Makefile" "COMMON_PACKAGES := ./common/..."
assert_file_contains "$TMPDIR/out-go/Makefile" "API_PACKAGES := ./api/backend ./api/cmd/api"
assert_file_contains "$TMPDIR/out-go/Makefile" "WORKER_PACKAGES := ./worker/backend ./worker/cmd/worker"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) test \$(COMMON_PACKAGES)"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) test \$(API_PACKAGES)"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) test \$(WORKER_PACKAGES)"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) build \$(COMMON_PACKAGES)"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) build ./api/backend"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) build -o \$(BIN_DIR)/statespec-api ./api/cmd/api"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) build ./worker/backend"
assert_file_contains "$TMPDIR/out-go/Makefile" "\$(GO) build -o \$(BIN_DIR)/statespec-worker ./worker/cmd/worker"
assert_file_contains "$TMPDIR/out-go/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-go/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-go/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-go/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-go/api/backend/api_descriptors.go" "type APITierDescriptor = common.ApiDescriptor"
assert_file_contains "$TMPDIR/out-go/api/backend/api_descriptors.go" "func APITierDescriptors"
assert_file_contains "$TMPDIR/out-go/api/backend/api_descriptors.go" "descriptors.StartOrderProcessingApiDescriptors"
assert_file_contains "$TMPDIR/out-go/api/backend/api_routes.go" "descriptors.StartOrderProcessingApiRouteDescriptors"
assert_file_contains "$TMPDIR/out-go/api/backend/descriptors/start_order_processing.go" "func StartOrderProcessingApiDescriptors"
assert_file_contains "$TMPDIR/out-go/api/backend/descriptors/start_order_processing.go" "func StartOrderProcessingApiRouteDescriptors"
assert_file_contains "$TMPDIR/out-go/api/backend/api_handlers.go" "type APITierHandler interface"
assert_file_contains "$TMPDIR/out-go/api/backend/api_handlers.go" "HandleStartOrderProcessing"
assert_file_contains "$TMPDIR/out-go/api/backend/codecs/start_order_processing_request.go" "func DecodeStartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-go/api/backend/codecs/start_order_processing_response.go" "func EncodeStartOrderProcessingResponse"
assert_file_contains "$TMPDIR/out-go/api/backend/api_handler_registry_order.go" "DecodeStartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-go/api/backend/api_handler_registry_order.go" "EncodeStartOrderProcessingResponseWithStatus"
assert_file_not_contains "$TMPDIR/out-go/api/backend/api_handler_registry.go" "handler_not_implemented"
assert_file_contains "$TMPDIR/out-go/api/backend/api_dispatcher.go" "func FindAPITierRoute"
assert_file_contains "$TMPDIR/out-go/api/backend/api_dispatcher.go" "func DispatchAPITierRoute"
assert_file_not_contains "$TMPDIR/out-go/api/backend/api_dispatcher.go" "func DispatchAPITierOperationRoute"
assert_file_contains "$TMPDIR/out-go/api/backend/api_server.go" "type APITierServer struct"
assert_file_contains "$TMPDIR/out-go/api/backend/api_server.go" "func FindAPITierServer"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "type APIProcess struct"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "func (process *APIProcess) Bootstrap"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "context.Context"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "context.CancelFunc"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "chan struct{}"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "started"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "func (process *APIProcess) Start(ctx context.Context) error"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "func (process *APIProcess) Join() error"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "func (process *APIProcess) Running() bool"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "EntityGCEnabled   bool"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "type EntityGCWorkerFunc"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "func (process *APIProcess) AddEntityGCWorker"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "startEntityGCWorkersLocked"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "type APITierTransport interface"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "return server.Handle(ctx, routeName, request)"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "type LocalBlockingAPITierTransport struct"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "func (transport *LocalBlockingAPITierTransport) Run"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "RequestStop()"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "func (transport *LocalBlockingAPITierTransport) RequestStop()"
assert_file_contains "$TMPDIR/out-go/api/backend/api_transport.go" "<-transport.stopCh"
assert_file_contains "$TMPDIR/out-go/api/backend/api_process.go" "process.Transport.RequestStop()"
assert_file_contains "$TMPDIR/out-go/api/cmd/api/main.go" "api.NewLocalBlockingAPITierTransport()"
assert_file_contains "$TMPDIR/out-go/api/backend/api_routes.go" "func APITierRouteDescriptors"
assert_file_contains "$TMPDIR/out-go/api/backend/external_system_operator_metadata_api.go" "APITierExternalSystemOperatorMetadataHandler"
assert_file_contains "$TMPDIR/out-go/api/backend/api_application.go" "Backend      common.Backend"
assert_file_not_contains "$TMPDIR/out-go/api/backend/api_application.go" "common/backend/memory"
assert_file_contains "$TMPDIR/out-go/api/cmd/api/main.go" "common/backend/memory"
assert_file_contains "$TMPDIR/out-go/api/cmd/api/main.go" "signal.NotifyContext"
assert_file_contains "$TMPDIR/out-go/api/cmd/api/main.go" "api.NewAPIProcess"
assert_file_contains "$TMPDIR/out-go/api/cmd/api/main.go" "process.Start(ctx)"
assert_file_contains "$TMPDIR/out-go/api/cmd/api/main.go" "process.Join()"
assert_file_not_contains "$TMPDIR/out-go/api/cmd/api/main.go" "NewDefaultAPITierApplication"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_descriptors.go" "type WorkerTierDescriptor = common.WorkerDescriptor"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_contexts.go" "func WorkerTierContexts"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_registry.go" "func FindWorkerTierDescriptor"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_application.go" "type WorkerTierApplication struct"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "type WorkerProcess struct"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "type WorkerProcessConfig struct"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "func (process *WorkerProcess) Start(ctx context.Context) error"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "func (process *WorkerProcess) Join() error"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "func (process *WorkerProcess) Running() bool"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "func (process *WorkerProcess) RequestStop()"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_process.go" "func (process *WorkerProcess) startWorkerLoops"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_step_handlers.go" "type WorkflowStepHandler interface"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_step_handlers.go" "type DefaultWorkflowStepHandler struct"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_step_handlers.go" "HandleOrderProcessingValidateOrder"
assert_file_not_contains "$TMPDIR/out-go/worker/backend/workflow_step_handlers.go" "HandleWorkflowStep"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_step_handlers.go" "func WorkflowStepHandlerKeys"
assert_file_exists "$TMPDIR/out-go/worker/backend/workflows/order_processing.go"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflows/order_processing.go" "HandleOrderProcessingValidateOrder"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_runner.go" "type WorkflowRunner struct"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_runner.go" "workflowmodules.DispatchOrderProcessingStep"
assert_file_contains "$TMPDIR/out-go/worker/backend/workflow_runner.go" "KeepAliveStep"
assert_file_not_exists "$TMPDIR/out-go/worker/backend/worker_handlers.go"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "func (runtime *WorkerTierRuntime) RunOnce"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "Backend      common.Backend"
assert_file_not_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "common/backend/memory"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "type WorkerTierRuntimeConfig struct"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "EntityGCEnabled      bool"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "type WorkerEntityGCWorkerFunc"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "func (runtime *WorkerTierRuntime) StartEntityGCWorkers"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "func (runtime *WorkerTierRuntime) RequestStop()"
assert_file_contains "$TMPDIR/out-go/worker/cmd/worker/main.go" "common/backend/memory"
assert_file_contains "$TMPDIR/out-go/worker/cmd/worker/main.go" "signal.NotifyContext"
assert_file_contains "$TMPDIR/out-go/worker/cmd/worker/main.go" "worker.DefaultWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-go/worker/cmd/worker/main.go" "worker.NewWorkerProcess"
assert_file_contains "$TMPDIR/out-go/worker/cmd/worker/main.go" "process.Start(ctx)"
assert_file_contains "$TMPDIR/out-go/worker/cmd/worker/main.go" "process.Join()"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_queues.go" "func WorkerTierQueueDefinitions"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_leases.go" "func WorkerTierLeaseDefinitions"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_workflows.go" "func WorkerTierWorkflowDefinitions"
assert_file_contains "$TMPDIR/out-go/common/backend/backend.go" "type FieldType string"
assert_file_contains "$TMPDIR/out-go/common/backend/backend.go" "FieldTypeString"
assert_file_contains "$TMPDIR/out-go/common/backend/backend.go" "Type     FieldType"
assert_file_contains "$TMPDIR/out-go/common/backend/backend.go" "TypeName string"
assert_file_contains "$TMPDIR/out-go/common/backend/workflow.go" "type KeepAliveWorkflowStepRequest struct"
assert_file_contains "$TMPDIR/out-go/common/backend/workflow.go" "KeepAliveStepTx"
assert_file_contains "$TMPDIR/out-go/common/backend/memory/backend.go" "type Backend struct"
assert_file_contains "$TMPDIR/out-go/common/backend/memory/transaction.go" "type Transaction struct"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/codec_feature_flags.go" "featureFlagDefinitionToJSON"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/codec_logs.go" "logDefinitionToJSON"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/codec_metrics.go" "metricDefinitionToJSON"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/feature_flags.go" "type FeatureFlagStore struct"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/queues.go" "type QueueStore struct"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/leases.go" "type LeaseStore struct"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/workflows.go" "type WorkflowStore struct"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/logs.go" "func (s *LogSink) InspectEvents"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/metrics.go" "func (s *MetricSink) InspectSamples"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/entity_gc_descriptors.go" "type EntityGCDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/entity_gc_descriptors.go" "common.OrderEntityName"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/entity_gc_descriptors.go" "common.OrderStatusFailed"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/entity_gc_repository.go" "type EntityGCRepository interface"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime/entity_gc_workers.go" "type EntityGCWorker struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type FeatureFlagDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func FeatureFlagDefinitions() []FeatureFlagDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ShapeDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/shape_descriptors.go" "func ShapeDescriptors() []ShapeDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/shapes/start_order_processing_request.go" "type StartOrderProcessingRequest struct"
assert_file_contains "$TMPDIR/out-go/common/backend/shapes/start_order_processing_request.go" "TenantId string"
assert_file_not_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type StartOrderProcessingRequest struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ValueDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func ValueDescriptors() []ValueDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EnumDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func EnumDescriptors() []EnumDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EventDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func EventDescriptors() []EventDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/events.go" "type EventEnvelope struct"
assert_file_contains "$TMPDIR/out-go/common/backend/events.go" "func NewOrderAcceptedEvent"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemMetadataDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemMetadataMappingDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemMetadataMappingPlan struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemOperatorMetadataUpsertRequest struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemOperatorMetadataRepository interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemMetadataMappingInputs struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemMetadataMissingMappingSource struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func MissingExternalSystemMetadataMappingSources"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func (i ExternalSystemMetadataMappingInputs) SourceValue"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemMetadataMappingApplicator interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type DefaultExternalSystemMetadataMappingApplicator struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type DefaultExternalSystemOperatorMetadataRepository struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func ExternalSystemMetadataKey"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemClient interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemCallRequest struct"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func BuildExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func CallExternalSystem"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func BuildExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "TenantField *string"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "KeyFields []string"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "TenantField: stringPtr(\"tenant_id\")"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "Source: \"metadata.base_url\""
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "Target: \"client.base_url\""
assert_file_contains "$TMPDIR/out-go/common/backend/external_system.go" "type ExternalSystemMetadataResolver interface"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func BuildExternalSystemMetadataLookup"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func ExternalSystemMetadataLookupByName"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func ResolveExternalSystemMetadataTx"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func ResolveExternalSystemMetadataByNameTx"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "KeyComplete()"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "func ExternalSystemDescriptors() []ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ApiDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func ApiDescriptors() []ApiDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ApiServerDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func ApiServerDescriptors() []ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ApiRouteDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type APIRequestContext struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type APIResponse struct"
assert_file_not_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type APIHandler interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type ExternalSystemOperatorMetadataAPIHandler interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func ApiRouteDescriptors() []ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "Name: \"OrderApi\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "Serves: []string{\"StartOrderProcessing\"}"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "Name: \"OrderApi.StartOrderProcessing\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "ServerName: \"OrderApi\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type WorkerDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type WorkerContext struct"
assert_file_not_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type Worker interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func WorkerDescriptors() []WorkerDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func WorkerContexts() []WorkerContext"
assert_file_contains "$TMPDIR/out-go/common/backend/worker_descriptor_order_worker.go" "Name: \"OrderWorker\""
assert_file_contains "$TMPDIR/out-go/common/backend/worker_descriptor_order_worker.go" "Polls: stringPtr(\"EmailDispatch.SendConfirmation\")"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type PolicyDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func PolicyDescriptors() []PolicyDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type GarbageCollectionPolicy struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EntityStateDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EntityOwnershipDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EntityRelationDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EntityChildDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EntityInvariantDescriptor struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type EntityRepository interface"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type DefaultEntityRepository struct"
assert_file_contains "$TMPDIR/out-go/common/backend/account_descriptors.go" "type AccountRepository interface"
assert_file_contains "$TMPDIR/out-go/common/backend/account_descriptors.go" "type DefaultAccountRepository struct"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "type OrderRepository interface"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "type DefaultOrderRepository struct"
assert_file_contains "$TMPDIR/out-go/common/backend/account_descriptors.go" "AccountEntityName"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "OrderFieldTenantId"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "OrderIndexByTenantStatus"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "OrderIndexByTenantOrder"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "{Name: OrderFieldTenantId"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "repository.ListByIndexTx(ctx, tx, OrderIndexByTenantStatus"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "repository.ListByIndexTx(ctx, tx, OrderIndexByTenantOrder"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "CreateTx"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "ListByIndexTx"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "ListByTenantStatusTx"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "ListByTenantOrderTx"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func EntityLookupFromDocument"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func EntityDescriptors() []EntityDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func CollectionDescriptors() []CollectionDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "Indexes: []IndexDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func QueueDefinitions() []QueueDefinition"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func LeaseDefinitions() []LeaseDescriptor"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func WorkflowDefinitions() []WorkflowDefinition"
assert_file_exists "$TMPDIR/out-go/common/backend/workflows/order_processing.go"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "EmailDispatch"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "OrderReconciler"
assert_file_contains "$TMPDIR/out-go/common/backend/workflows/order_processing.go" "WorkflowVersion: 2"
assert_file_contains "$TMPDIR/out-go/common/backend/workflows/order_processing.go" "validate_order"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "NewScheduler"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "DefaultValue: \"false\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "OrderAmount"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "OrderStatus"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "OrderAccepted"
assert_file_contains "$TMPDIR/out-go/common/backend/external_systems.go" "Stripe"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "Path: stringPtr(\"/v1/tenants/{tenantId}/orders/{order_id}/start\")"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "OrderAccess"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type LogDefinition struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func LogDefinitions() []LogDefinition"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "EventName: \"workflow.launch.decision\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "type MetricDefinition struct"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func MetricDefinitions() []MetricDefinition"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func EnsureSystemCollections(ctx context.Context, backend Backend) error"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime_registration_feature_flags.go" "func RegisterFeatureFlagDefinitionsTx"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime_registration_queues.go" "func RegisterQueueDefinitionsTx"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime_registration_leases.go" "func RegisterLeaseDefinitionsTx"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func RegisterRuntimeCatalogTx"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func RegisterRuntimeCatalog("
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "func BootstrapRuntimeCatalog("
assert_file_contains "$TMPDIR/out-go/common/backend/runtime_registration_observability.go" "func RegisterObservabilityCatalogTx"
assert_file_contains "$TMPDIR/out-go/common/backend/runtime_registration_workflows.go" "func RegisterWorkflowDefinitionsTx"
assert_file_contains "$TMPDIR/out-go/api/backend/api_application.go" "func (app *APITierApplication) Bootstrap"
assert_file_contains "$TMPDIR/out-go/worker/backend/worker_runtime.go" "func (runtime *WorkerTierRuntime) Bootstrap"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "BackendName: \"workflow_launch_attempts_total\""
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "Metadata: JSONObject(map[string]JSON{})"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "RelationKind: stringPtr(\"composition\")"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "Name: \"valid_status\""
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "Name: OrderIndexByTenantStatus"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "Unique: true"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "GarbageCollection: &GarbageCollectionPolicy{After: \"P30D\", Mode: \"tombstone\"}"
assert_file_contains "$TMPDIR/out-go/common/backend/start_order_processing_request_shape_descriptors.go" "Type: FieldTypeString"
assert_file_contains "$TMPDIR/out-go/common/backend/descriptors.go" "Type: FieldTypeNamed"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "Type: FieldTypeTimestamp"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "Type: FieldTypeOptional"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "OrderFieldStatusTypeName = \"string\""
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "OrderFieldRetryCountTypeName = \"int?\""
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "{Name: OrderFieldStatus, Type: FieldTypeString, TypeName: OrderFieldStatusTypeName, Required: true}"
assert_file_contains "$TMPDIR/out-go/common/backend/order_descriptors.go" "TypeName: OrderFieldRetryCountTypeName"

cp "$SCRIPT_DIR/metadata_resolver_fixture_test.go" "$TMPDIR/out-go/common/backend/metadata_resolver_fixture_test.go"
cp "$SCRIPT_DIR/runtime_fixture_test.go" "$TMPDIR/out-go/common/backend/runtime/runtime_fixture_test.go"
(cd "$TMPDIR/out-go" && go test ./...)
