#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

# Positive generation: Rust.
run_expect_status 0 "$CLI" generate bindings --lang rust "$SPEC" --out "$TMPDIR/out-rust"
assert_output_contains "generated $TMPDIR/out-rust/common/backend.rs"
assert_file_exists "$TMPDIR/out-rust/common/json.rs"
assert_file_exists "$TMPDIR/out-rust/common/backend.rs"
assert_file_exists "$TMPDIR/out-rust/common/external_system.rs"
assert_file_exists "$TMPDIR/out-rust/common/feature_flag.rs"
assert_file_exists "$TMPDIR/out-rust/common/lease.rs"
assert_file_exists "$TMPDIR/out-rust/common/log.rs"
assert_file_exists "$TMPDIR/out-rust/common/metric.rs"
assert_file_exists "$TMPDIR/out-rust/common/queue.rs"
assert_file_exists "$TMPDIR/out-rust/common/workflow.rs"
assert_file_exists "$TMPDIR/out-rust/common/descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/Cargo.toml"
assert_file_exists "$TMPDIR/out-rust/lib.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_handlers.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_routes.rs"
assert_file_exists "$TMPDIR/out-rust/api/external_system_operator_metadata_api.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_contexts.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_handlers.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_queues.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_leases.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_workflows.rs"
assert_file_contains "$TMPDIR/out-rust/Cargo.toml" "name = \"statespec-generated\""
assert_file_contains "$TMPDIR/out-rust/Cargo.toml" "path = \"lib.rs\""
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_handlers;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_routes;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_contexts;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_workflows;"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "pub use crate::descriptors::{ApiDescriptor, ApiServerDescriptor}"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "pub fn api_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "pub use crate::descriptors::{ApiHandler, ApiRequestContext, ApiResponse}"
assert_file_contains "$TMPDIR/out-rust/api/api_routes.rs" "pub fn api_route_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/external_system_operator_metadata_api.rs" "ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-rust/worker/worker_descriptors.rs" "pub fn worker_descriptors"
assert_file_contains "$TMPDIR/out-rust/worker/worker_contexts.rs" "pub fn worker_contexts"
assert_file_contains "$TMPDIR/out-rust/worker/worker_handlers.rs" "pub use crate::descriptors::Worker"
assert_file_contains "$TMPDIR/out-rust/worker/worker_queues.rs" "pub fn queue_definitions"
assert_file_contains "$TMPDIR/out-rust/worker/worker_leases.rs" "pub fn lease_definitions"
assert_file_contains "$TMPDIR/out-rust/worker/worker_workflows.rs" "pub fn workflow_definitions"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub enum FieldType"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub field_type: FieldType"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub type_name: String"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn feature_flag_definitions() -> Vec<FeatureFlagDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ShapeDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn shape_descriptors() -> Vec<ShapeDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub tenant_id: String"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ValueDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn value_descriptors() -> Vec<ValueDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EnumDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn enum_descriptors() -> Vec<EnumDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EventDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn event_descriptors() -> Vec<EventDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EventEnvelope"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn make_order_accepted_event"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn missing_external_system_metadata_mapping_sources"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn source_value"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_mapping_plan"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub tenant_field: Option<String>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub key_fields: Vec<String>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "tenant_field: Some(\"tenant_id\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "source: \"metadata.base_url\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "target: \"client.base_url\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/external_system.rs" "pub trait ExternalSystemMetadataResolver"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_lookup"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_lookup_by_name"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn resolve_external_system_metadata_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn resolve_external_system_metadata_by_name_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "key_complete()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_descriptors() -> Vec<ExternalSystemDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_descriptors() -> Vec<ApiDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_server_descriptors() -> Vec<ApiServerDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiRequestContext"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiResponse"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ApiHandler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_route_descriptors() -> Vec<ApiRouteDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"OrderApi\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "serves: vec![\"StartOrderProcessing\".to_string()]"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"OrderApi.StartOrderProcessing\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "server_name: \"OrderApi\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct WorkerDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct WorkerContext"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait Worker"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn worker_descriptors() -> Vec<WorkerDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn worker_contexts() -> Vec<WorkerContext>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"OrderWorker\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "polls: Some(\"EmailDispatch.SendConfirmation\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct PolicyDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn policy_descriptors() -> Vec<PolicyDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityInvariantDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn entity_descriptors() -> Vec<EntityDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn collection_descriptors() -> Vec<CollectionDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "IndexDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn queue_definitions() -> Vec<QueueDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn lease_definitions() -> Vec<LeaseDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn workflow_definitions() -> Vec<WorkflowDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "EmailDispatch"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderReconciler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "workflow_version: 2"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "validate_order"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "NewScheduler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderAmount"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderStatus"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderAccepted"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "Stripe"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "path: Some(\"/v1/tenants/{tenantId}/orders/{order_id}/start\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderAccess"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct LogDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn log_definitions() -> Vec<LogDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "event_name: \"workflow.launch.decision\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct MetricDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn metric_definitions() -> Vec<MetricDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn ensure_system_collections"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_feature_flag_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_queue_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_lease_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_runtime_catalog_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_observability_catalog_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_workflow_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "backend_name: \"workflow_launch_attempts_total\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "relation_kind: Some(\"composition\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"valid_status\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"by_tenant_status\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "unique: true"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "garbage_collection: Some(GarbageCollectionPolicy { after: \"P30D\".to_string(), mode: \"tombstone\".to_string() })"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::String"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::Named"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::Timestamp"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::Optional"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "type_name: \"OrderStatus\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "type_name: \"int?\".to_string()"
mkdir -p "$TMPDIR/out-rust/tests"
cp "$SCRIPT_DIR/metadata_resolver_fixture.rs" "$TMPDIR/out-rust/tests/metadata_resolver_fixture.rs"
(cd "$TMPDIR/out-rust" && CARGO_TARGET_DIR="$TMPDIR/rust-target" cargo test)
