#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

# Positive generation: Rust.
run_expect_status 0 "$CLI" generate bindings --lang rust "$SPEC" --out "$TMPDIR/out-rust"
assert_output_contains "generated $TMPDIR/out-rust/common/backend.rs"
assert_file_exists "$TMPDIR/out-rust/common/json.rs"
assert_file_exists "$TMPDIR/out-rust/common/backend.rs"
assert_file_exists "$TMPDIR/out-rust/common/external_system.rs"
assert_file_exists "$TMPDIR/out-rust/common/feature_flag.rs"
assert_file_exists "$TMPDIR/out-rust/common/lease.rs"
assert_file_exists "$TMPDIR/out-rust/common/log.rs"
assert_file_exists "$TMPDIR/out-rust/common/metric.rs"
assert_file_exists "$TMPDIR/out-rust/common/queue.rs"
assert_file_exists "$TMPDIR/out-rust/common/workflow.rs"
assert_file_exists "$TMPDIR/out-rust/common/memory/backend.rs"
assert_file_exists "$TMPDIR/out-rust/common/memory/transaction.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_core.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_feature_flags.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_queues.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_leases.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_workflows.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_observability.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_logs.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/codec_metrics.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/feature_flags.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/queues.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/leases.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/workflows.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/logs.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/metrics.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/entity_gc_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/entity_gc_repository.rs"
assert_file_exists "$TMPDIR/out-rust/common/runtime/entity_gc_workers.rs"
assert_file_exists "$TMPDIR/out-rust/common/descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/Cargo.toml"
assert_file_exists "$TMPDIR/out-rust/Makefile"
assert_file_exists "$TMPDIR/out-rust/lib.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_codecs.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_handlers.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_dispatcher.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_process.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_server.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_transport.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_routes.rs"
assert_file_exists "$TMPDIR/out-rust/api/external_system_operator_metadata_api.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_contexts.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_registry.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_application.rs"
assert_file_exists "$TMPDIR/out-rust/worker/workflow_step_handlers.rs"
assert_file_exists "$TMPDIR/out-rust/worker/workflow_runner.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_queues.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_leases.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_workflows.rs"
assert_file_contains "$TMPDIR/out-rust/Cargo.toml" "name = \"statespec-generated\""
assert_file_contains "$TMPDIR/out-rust/Cargo.toml" "path = \"lib.rs\""
assert_file_contains "$TMPDIR/out-rust/Makefile" "CARGO ?= cargo"
assert_file_contains "$TMPDIR/out-rust/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-rust/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-rust/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-rust/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_codecs;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_handlers;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_dispatcher;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_process;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_server;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_transport;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_routes;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_contexts;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_registry;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_application;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod workflow_step_handlers;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod workflow_runner;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_workflows;"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "pub use crate::descriptors::{ApiDescriptor, ApiServerDescriptor}"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "pub fn api_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "pub use crate::descriptors::{ApiRequestContext, ApiResponse}"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "pub trait ApiHandler"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "handle_start_order_processing"
assert_file_contains "$TMPDIR/out-rust/api/api_codecs.rs" "decode_start_order_processing_request"
assert_file_contains "$TMPDIR/out-rust/api/api_codecs.rs" "encode_start_order_processing_response"
assert_file_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "decode_start_order_processing_request"
assert_file_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "encode_start_order_processing_response_with_status"
assert_file_not_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "handler_not_implemented"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn find_api_route"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn dispatch_api_route"
assert_file_not_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn dispatch_api_operation_route"
assert_file_contains "$TMPDIR/out-rust/api/api_server.rs" "pub struct ApiServer"
assert_file_contains "$TMPDIR/out-rust/api/api_server.rs" "pub fn find_api_server"
assert_file_contains "$TMPDIR/out-rust/api/api_routes.rs" "pub fn api_route_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/external_system_operator_metadata_api.rs" "ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-rust/api/api_application.rs" "pub struct ApiApplication<B: Backend"
assert_file_not_contains "$TMPDIR/out-rust/api/api_application.rs" "memory_backend"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub struct ApiProcess"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn bootstrap(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn request_stop(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "Arc<Mutex<ApiProcessLifecycle>>"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "JoinHandle<BackendResult<()>>"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn start(self: &Arc<Self>)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn join(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn is_running(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub entity_gc_enabled: bool"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub type EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn add_entity_gc_worker"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "fn start_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "pub trait ApiTransport"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "server.handle(route_name, context)"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "pub struct LocalBlockingApiTransport"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "fn run(&self) -> BackendResult<()>"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "fn request_stop(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" ".stop_requested"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "self.transport.request_stop()"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "use crate::memory_backend::InMemoryBackend"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "LocalBlockingApiTransport::new()"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "ApiProcessConfig::all_servers"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "install_signal_handling"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "process.start()"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "process.join()"
assert_file_not_contains "$TMPDIR/out-rust/api/main.rs" "ApiApplication::new_default"
assert_file_contains "$TMPDIR/out-rust/worker/worker_descriptors.rs" "pub fn worker_descriptors"
assert_file_contains "$TMPDIR/out-rust/worker/worker_contexts.rs" "pub fn worker_contexts"
assert_file_contains "$TMPDIR/out-rust/worker/worker_registry.rs" "pub fn find_worker_descriptor"
assert_file_contains "$TMPDIR/out-rust/worker/worker_application.rs" "pub struct WorkerApplication"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "pub trait WorkflowStepHandler"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "handle_order_processing_validate_order"
assert_file_not_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "handle_workflow_step"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "pub fn workflow_step_handler_keys"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_runner.rs" "pub struct WorkflowRunner"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_runner.rs" "handle_order_processing_validate_order"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_runner.rs" "keep_alive_step"
assert_file_not_exists "$TMPDIR/out-rust/worker/worker_handlers.rs"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn run_once"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub struct WorkerRuntime<B: Backend>"
assert_file_not_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "memory_backend"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub struct WorkerRuntimeConfig"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub entity_gc_enabled: bool"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub type WorkerEntityGcTask"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn start_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn request_stop"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "use crate::memory_backend::InMemoryBackend"
assert_file_contains "$TMPDIR/out-rust/worker/worker_queues.rs" "pub fn queue_definitions"
assert_file_contains "$TMPDIR/out-rust/worker/worker_leases.rs" "pub fn lease_definitions"
assert_file_contains "$TMPDIR/out-rust/worker/worker_workflows.rs" "pub fn workflow_definitions"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub enum FieldType"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub field_type: FieldType"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub type_name: String"
assert_file_contains "$TMPDIR/out-rust/common/workflow.rs" "pub struct KeepAliveWorkflowStepRequest"
assert_file_contains "$TMPDIR/out-rust/common/workflow.rs" "fn keep_alive_step_tx"
assert_file_contains "$TMPDIR/out-rust/common/memory/backend.rs" "pub struct InMemoryBackend"
assert_file_contains "$TMPDIR/out-rust/common/memory/transaction.rs" "pub struct InMemoryTransaction"
assert_file_contains "$TMPDIR/out-rust/common/runtime/codec_feature_flags.rs" "feature_flag_definition_to_json"
assert_file_contains "$TMPDIR/out-rust/common/runtime/codec_logs.rs" "log_definition_to_json"
assert_file_contains "$TMPDIR/out-rust/common/runtime/codec_metrics.rs" "metric_definition_to_json"
assert_file_contains "$TMPDIR/out-rust/common/runtime/feature_flags.rs" "pub struct RuntimeFeatureFlagStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/queues.rs" "pub struct RuntimeQueueStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/leases.rs" "pub struct RuntimeLeaseStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/workflows.rs" "pub struct RuntimeWorkflowStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/logs.rs" "inspect_events"
assert_file_contains "$TMPDIR/out-rust/common/runtime/metrics.rs" "inspect_samples"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_descriptors.rs" "pub struct EntityGcDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_repository.rs" "pub trait EntityGcRepository"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_workers.rs" "pub struct EntityGcWorker"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn feature_flag_definitions() -> Vec<FeatureFlagDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ShapeDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn shape_descriptors() -> Vec<ShapeDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub tenant_id: String"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ValueDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn value_descriptors() -> Vec<ValueDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EnumDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn enum_descriptors() -> Vec<EnumDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EventDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn event_descriptors() -> Vec<EventDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EventEnvelope"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn make_order_accepted_event"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn missing_external_system_metadata_mapping_sources"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn source_value"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemClient"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn build_external_system_call_request"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn call_external_system"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_key"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_mapping_plan"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub tenant_field: Option<String>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub key_fields: Vec<String>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "tenant_field: Some(\"tenant_id\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "source: \"metadata.base_url\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "target: \"client.base_url\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/external_system.rs" "pub trait ExternalSystemMetadataResolver"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_lookup"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_lookup_by_name"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn resolve_external_system_metadata_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn resolve_external_system_metadata_by_name_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "key_complete()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_descriptors() -> Vec<ExternalSystemDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_descriptors() -> Vec<ApiDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_server_descriptors() -> Vec<ApiServerDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiRequestContext"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiResponse"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ApiHandler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_route_descriptors() -> Vec<ApiRouteDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"OrderApi\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "serves: vec![\"StartOrderProcessing\".to_string()]"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"OrderApi.StartOrderProcessing\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "server_name: \"OrderApi\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct WorkerDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct WorkerContext"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait Worker"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn worker_descriptors() -> Vec<WorkerDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn worker_contexts() -> Vec<WorkerContext>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"OrderWorker\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "polls: Some(\"EmailDispatch.SendConfirmation\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct PolicyDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn policy_descriptors() -> Vec<PolicyDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityInvariantDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait EntityRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultEntityRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait AccountRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultAccountRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait OrderRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "create_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "list_by_index_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn entity_lookup_from_document"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn entity_descriptors() -> Vec<EntityDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn collection_descriptors() -> Vec<CollectionDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "IndexDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn queue_definitions() -> Vec<QueueDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn lease_definitions() -> Vec<LeaseDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn workflow_definitions() -> Vec<WorkflowDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "EmailDispatch"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderReconciler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "workflow_version: 2"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "validate_order"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "NewScheduler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderAmount"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderStatus"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderAccepted"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "Stripe"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "path: Some(\"/v1/tenants/{tenantId}/orders/{order_id}/start\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "OrderAccess"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct LogDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn log_definitions() -> Vec<LogDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "event_name: \"workflow.launch.decision\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct MetricDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn metric_definitions() -> Vec<MetricDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn ensure_system_collections"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_feature_flag_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_queue_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_lease_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_runtime_catalog_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_runtime_catalog"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn bootstrap_runtime_catalog"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_observability_catalog_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn register_workflow_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/api/api_application.rs" "pub fn bootstrap(&self)"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn bootstrap(&self)"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "backend_name: \"workflow_launch_attempts_total\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "relation_kind: Some(\"composition\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"valid_status\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"by_tenant_status\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "unique: true"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "garbage_collection: Some(GarbageCollectionPolicy { after: \"P30D\".to_string(), mode: \"tombstone\".to_string() })"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::String"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::Named"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::Timestamp"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "field_type: FieldType::Optional"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "type_name: \"OrderStatus\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "type_name: \"int?\".to_string()"
mkdir -p "$TMPDIR/out-rust/tests"
cp "$SCRIPT_DIR/metadata_resolver_fixture.rs" "$TMPDIR/out-rust/tests/metadata_resolver_fixture.rs"
cp "$SCRIPT_DIR/memory_backend_fixture.rs" "$TMPDIR/out-rust/tests/memory_backend_fixture.rs"
(cd "$TMPDIR/out-rust" && CARGO_TARGET_DIR="$TMPDIR/rust-target" cargo test)
