#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
. "$SCRIPT_DIR/../common.sh"
binding_test_init "$1" "$0"

OUT="$TMPDIR/out-rust"

generate_binding_fixture rust "$OUT" "common/backend.rs"

# Common runtime, descriptor, and entity/API/Worker artifacts.
assert_generated_files_exist "$OUT" <<'EOF'
common/json.rs
common/backend.rs
common/external_system.rs
common/feature_flag.rs
common/lease.rs
common/log.rs
common/metric.rs
common/queue.rs
common/workflow.rs
common/memory/backend.rs
common/memory/transaction.rs
common/runtime/codec.rs
common/runtime/codec_core.rs
common/runtime/codec_feature_flags.rs
common/runtime/codec_queues.rs
common/runtime/codec_leases.rs
common/runtime/codec_workflows.rs
common/runtime/codec_observability.rs
common/runtime/codec_logs.rs
common/runtime/codec_metrics.rs
common/runtime/feature_flags.rs
common/runtime/queues.rs
common/runtime/leases.rs
common/runtime/workflows.rs
common/runtime/logs.rs
common/runtime/metrics.rs
common/runtime/entity_gc_types.rs
common/runtime/entity_gc_repository.rs
common/runtime/entity_gc_workers.rs
common/runtime/entity_gc_registration.rs
common/entities/order/gc.rs
common/descriptors.rs
common/descriptors/types.rs
common/shape_types.rs
common/entity_repository.rs
common/runtime_registration.rs
api/shapes.rs
api/shapes/start_order_processing_request.rs
common/descriptors/core.rs
common/descriptors/policies.rs
common/descriptors/observability.rs
common/descriptors/runtime.rs
worker/descriptors/catalog.rs
worker/descriptors/order_worker.rs
common/entities/account/model.rs
common/entities/account/constants.rs
common/entities/account/persistence.rs
common/entities/account/schema.rs
common/entities/order/model.rs
common/entities/order/constants.rs
common/entities/order/persistence.rs
common/entities/order/schema.rs
EOF

# Legacy aggregate artifacts that should stay removed.
assert_generated_files_absent "$OUT" <<'EOF'
common/runtime/entity_gc_descriptors.rs
common/descriptors/shapes.rs
common/descriptors/shapes/start_order_processing_request.rs
common/descriptors/apis.rs
common/descriptors/workers.rs
common/descriptors/entities/account.rs
common/descriptors/entities/order.rs
EOF
assert_file_contains "$TMPDIR/out-rust/common/entities/account/constants.rs" "ACCOUNT_ENTITY_NAME: &str = \"Account\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/constants.rs" "ORDER_INDEX_BY_TENANT_STATUS: &str = \"by_tenant_status\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "pub fn order_field_descriptors() -> Vec<FieldDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "pub fn order_index_descriptors() -> Vec<IndexDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/constants.rs" "ORDER_RELATION_ACCOUNT_ID_TARGET: &str = \"Account\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/schema.rs" "ORDER_SCHEMA_VERSION: u64 = 1"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/schema.rs" "ORDER_OWNERSHIP_LIFECYCLE: &str = \"authoritative\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/schema.rs" "ORDER_STATE_FAILED_GC_AFTER: &str = \"P30D\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/schema.rs" "pub fn order_collection_descriptor() -> CollectionDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "pub trait OrderRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "pub struct DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "fn list_by_tenant_status_tx"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "pub fn order_lookup"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "#[path = \"descriptors/core.rs\"]"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "mod descriptor_entity_account;"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "mod descriptor_entity_order;"
assert_file_contains "$TMPDIR/out-rust/common/entities/account/constants.rs" "pub const ACCOUNT_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-rust/common/entities/account/persistence.rs" "pub struct DefaultAccountRepository;"
assert_file_exists "$TMPDIR/out-rust/Cargo.toml"
assert_file_exists "$TMPDIR/out-rust/Makefile"
assert_file_exists "$TMPDIR/out-rust/lib.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/api/descriptors/catalog.rs"
assert_file_exists "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_codecs.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_handlers.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_dispatcher.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_process.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_server.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_transport.rs"
assert_file_exists "$TMPDIR/out-rust/api/api_routes.rs"
assert_file_exists "$TMPDIR/out-rust/api/external_system_operator_metadata_api.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_descriptors.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_contexts.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_registry.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_application.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_process.rs"
assert_file_exists "$TMPDIR/out-rust/worker/workflow_step_handlers.rs"
assert_file_exists "$TMPDIR/out-rust/worker/workflow_runner.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_queues.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_leases.rs"
assert_file_exists "$TMPDIR/out-rust/worker/worker_workflows.rs"
assert_file_contains "$TMPDIR/out-rust/Cargo.toml" "name = \"statespec-generated\""
assert_file_contains "$TMPDIR/out-rust/Cargo.toml" "path = \"lib.rs\""
assert_file_contains "$TMPDIR/out-rust/Makefile" "CARGO ?= cargo"
assert_file_contains "$TMPDIR/out-rust/Makefile" "help:"
assert_file_contains "$TMPDIR/out-rust/Makefile" "Default target: all -> check"
assert_file_contains "$TMPDIR/out-rust/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-rust/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-rust/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-rust/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod descriptor_types;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_codecs;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_handlers;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_dispatcher;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_process;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_entity_gc_catalog;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_server;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_transport;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod api_routes;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_descriptors;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_contexts;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_registry;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_application;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_process;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_entity_gc_catalog;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod workflow_step_handlers;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod workflow_runner;"
assert_file_contains "$TMPDIR/out-rust/lib.rs" "pub mod worker_workflows;"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "pub use crate::descriptor_types::{ApiDescriptor, ApiRouteDescriptor, ApiServerDescriptor}"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "pub fn api_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/api_descriptors.rs" "catalog::api_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/catalog.rs" "api_descriptor_start_order_processing::start_order_processing_api_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/catalog.rs" "use crate::descriptor_types::{ApiDescriptor, ApiRouteDescriptor, ApiServerDescriptor}"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/catalog.rs" "api_descriptor_start_order_processing::start_order_processing_api_route_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "pub fn start_order_processing_api_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "use crate::descriptor_types::{ApiDescriptor, ApiRouteDescriptor}"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "pub fn start_order_processing_api_route_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "pub use crate::descriptor_types::{ApiRequestContext, ApiResponse}"
assert_file_not_contains "$TMPDIR/out-rust/api/api_handlers.rs" "pub trait ApiHandler"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "handle_start_order_processing"
assert_file_contains "$TMPDIR/out-rust/api/codecs/start_order_processing_request.rs" "decode_start_order_processing_request"
assert_file_contains "$TMPDIR/out-rust/api/codecs/start_order_processing_response.rs" "encode_start_order_processing_response"
assert_file_contains "$TMPDIR/out-rust/api/api_handlers.rs" "pub trait BusinessApiHandler"
assert_file_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "handler.handle_start_order_processing"
assert_file_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "pub fn register_handler_invokers<B: Backend>"
assert_file_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "pub fn register_business_handler_invokers"
assert_file_not_exists "$TMPDIR/out-rust/api/entities/order/handlers.rs"
assert_file_not_contains "$TMPDIR/out-rust/api/api_handler_registry.rs" "handler_not_implemented"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn find_api_route"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn dispatch_api_route"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn api_route_lookup_map"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn api_handler_lookup_map"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub type ApiHandlerInvoker<B> = fn(&B, &ApiRequestContext) -> BackendResult<ApiResponse>;"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub type BusinessApiHandlerInvoker"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "OnceLock<HashMap<String, ApiRouteDescriptor>>"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "OnceLock<HashMap<&'static str, BusinessApiHandlerInvoker>>"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "api_route_lookup_map().get(route_name).cloned()"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "api_handler_lookup_map::<B>()"
assert_file_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "api_handler_registry::register_handler_invokers::<B>(&mut handlers)"
assert_file_not_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "dyn ApiHandler"
assert_file_not_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "match route.api_name.as_str()"
assert_file_not_contains "$TMPDIR/out-rust/api/api_dispatcher.rs" "pub fn dispatch_api_operation_route"
assert_file_contains "$TMPDIR/out-rust/api/api_server.rs" "pub struct ApiServer"
assert_file_contains "$TMPDIR/out-rust/api/api_server.rs" "pub fn find_api_server"
assert_file_contains "$TMPDIR/out-rust/api/api_routes.rs" "pub fn api_route_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/external_system_operator_metadata_api.rs" "ExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-rust/api/api_application.rs" "pub struct ApiApplication<B: Backend"
assert_file_not_contains "$TMPDIR/out-rust/api/api_application.rs" "memory_backend"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub struct ApiProcess"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn bootstrap(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn request_stop(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "Arc<Mutex<ApiProcessLifecycle>>"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "JoinHandle<BackendResult<()>>"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn start(self: &Arc<Self>)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn join(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn is_running(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub entity_gc_enabled: bool"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub type EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "pub fn add_entity_gc_worker"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "fn start_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "pub trait ApiTransport"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "server.handle(route_name, context)"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "pub struct LocalBlockingApiTransport"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "fn run(&self) -> BackendResult<()>"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" "fn request_stop(&self)"
assert_file_contains "$TMPDIR/out-rust/api/api_transport.rs" ".stop_requested"
assert_file_contains "$TMPDIR/out-rust/api/api_process.rs" "self.transport.request_stop()"
assert_file_exists "$TMPDIR/out-rust/api/entity_gc_catalog.rs"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "use crate::memory_backend::InMemoryBackend"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "use crate::api_entity_gc_catalog::entity_gc_descriptors"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "use crate::runtime_entity_gc_registration::register_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "LocalBlockingApiTransport::new()"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "ApiProcessConfig::all_servers"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "register_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "api_entity_gc_descriptors()"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "process.add_entity_gc_worker"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "install_signal_handling"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "process.start()"
assert_file_contains "$TMPDIR/out-rust/api/entity_gc_catalog.rs" "pub fn entity_gc_descriptors()"
assert_file_contains "$TMPDIR/out-rust/api/entity_gc_catalog.rs" "order_entity_gc_descriptor()"
assert_file_contains "$TMPDIR/out-rust/api/main.rs" "process.join()"
assert_file_not_contains "$TMPDIR/out-rust/api/main.rs" "ApiApplication::new_default"
assert_file_contains "$TMPDIR/out-rust/worker/worker_descriptors.rs" "pub fn worker_descriptors"
assert_file_contains "$TMPDIR/out-rust/worker/worker_contexts.rs" "pub fn worker_contexts"
assert_file_contains "$TMPDIR/out-rust/worker/worker_registry.rs" "pub fn find_worker_descriptor"
assert_file_contains "$TMPDIR/out-rust/worker/worker_application.rs" "pub struct WorkerApplication"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "pub struct WorkerProcess"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "pub struct WorkerProcessConfig"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "pub fn start(self: &Arc<Self>)"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "pub fn join(&self)"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "pub fn is_running(&self)"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "pub fn request_stop(&self)"
assert_file_contains "$TMPDIR/out-rust/worker/worker_process.rs" "fn start_worker_loops"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "pub trait WorkflowStepHandler"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "pub struct DefaultWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "handle_order_processing_validate_order"
assert_file_not_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "handle_workflow_step"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_step_handlers.rs" "pub fn workflow_step_handler_keys"
assert_file_exists "$TMPDIR/out-rust/worker/workflows/order_processing.rs"
assert_file_contains "$TMPDIR/out-rust/worker/workflows/order_processing.rs" "handle_order_processing_validate_order"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_runner.rs" "pub struct WorkflowRunner"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_runner.rs" "workflow_order_processing::dispatch_step"
assert_file_contains "$TMPDIR/out-rust/worker/workflow_runner.rs" "keep_alive_step"
assert_file_not_exists "$TMPDIR/out-rust/worker/worker_handlers.rs"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn run_once"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub struct WorkerRuntime<B: Backend>"
assert_file_not_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "memory_backend"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub struct WorkerRuntimeConfig"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub entity_gc_enabled: bool"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub type WorkerEntityGcTask"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn start_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn request_stop"
assert_file_exists "$TMPDIR/out-rust/worker/entity_gc_catalog.rs"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "use crate::memory_backend::InMemoryBackend"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "use crate::runtime_entity_gc_registration::register_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "use crate::worker_entity_gc_catalog::entity_gc_descriptors"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "DefaultWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "WorkerProcess::new"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "register_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "worker_entity_gc_descriptors()"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "process.runtime.add_entity_gc_worker"
assert_file_contains "$TMPDIR/out-rust/worker/entity_gc_catalog.rs" "pub fn entity_gc_descriptors()"
assert_file_contains "$TMPDIR/out-rust/worker/entity_gc_catalog.rs" "order_entity_gc_descriptor()"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "install_signal_handling"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "process.start()"
assert_file_contains "$TMPDIR/out-rust/worker/main.rs" "process.join()"
assert_file_contains "$TMPDIR/out-rust/worker/worker_queues.rs" "pub fn queue_definitions"
assert_file_contains "$TMPDIR/out-rust/worker/worker_leases.rs" "pub fn lease_definitions"
assert_file_contains "$TMPDIR/out-rust/worker/worker_leases.rs" "pub use crate::lease::LeaseDefinition"
assert_file_contains "$TMPDIR/out-rust/worker/worker_workflows.rs" "pub fn workflow_definitions"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub enum FieldType"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub field_type: FieldType"
assert_file_contains "$TMPDIR/out-rust/common/backend.rs" "pub type_name: String"
assert_file_contains "$TMPDIR/out-rust/common/workflow.rs" "pub struct KeepAliveWorkflowStepRequest"
assert_file_contains "$TMPDIR/out-rust/common/workflow.rs" "fn keep_alive_step_tx"
assert_file_contains "$TMPDIR/out-rust/common/memory/backend.rs" "pub struct InMemoryBackend"
assert_file_contains "$TMPDIR/out-rust/common/memory/transaction.rs" "pub struct InMemoryTransaction"
assert_file_contains "$TMPDIR/out-rust/common/runtime/codec_feature_flags.rs" "feature_flag_definition_to_json"
assert_file_contains "$TMPDIR/out-rust/common/runtime/codec_logs.rs" "log_definition_to_json"
assert_file_contains "$TMPDIR/out-rust/common/runtime/codec_metrics.rs" "metric_definition_to_json"
assert_file_contains "$TMPDIR/out-rust/common/runtime/feature_flags.rs" "pub struct RuntimeFeatureFlagStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/queues.rs" "pub struct RuntimeQueueStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/leases.rs" "pub struct RuntimeLeaseStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/workflows.rs" "pub struct RuntimeWorkflowStore"
assert_file_contains "$TMPDIR/out-rust/common/runtime/logs.rs" "inspect_events"
assert_file_contains "$TMPDIR/out-rust/common/runtime/metrics.rs" "inspect_samples"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_types.rs" "pub struct EntityGcDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_types.rs" "entity_gc_descriptors"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_types.rs" "order_entity_gc_descriptor"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/mod.rs" "pub mod gc;"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/gc.rs" "pub fn order_entity_gc_descriptor() -> crate::runtime_entity_gc_types::EntityGcDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/gc.rs" "entity: constants::ORDER_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/gc.rs" "state: constants::ORDER_STATUS_FAILED"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/gc.rs" "after: schema::ORDER_STATE_FAILED_GC_AFTER"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_repository.rs" "pub trait EntityGcRepository"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_workers.rs" "pub struct EntityGcWorker"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "pub struct DefaultEntityGcRepository"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "pub fn register_entity_gc_workers"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "descriptors: Vec<EntityGcDescriptor>"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "register_entity_gc_workers_with_descriptors"
assert_file_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "for descriptor in descriptors"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "Scheduler"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "lease"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "queue"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "workflow"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "feature_flag"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "log"
assert_file_not_contains "$TMPDIR/out-rust/common/runtime/entity_gc_registration.rs" "metric"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "pub fn feature_flag_definitions() -> Vec<FeatureFlagDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "FeatureFlagType::Bool"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "FeatureFlagValue::Bool(false)"
assert_file_contains "$TMPDIR/out-rust/common/shape_types.rs" "pub struct ShapeDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ShapeDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn shape_descriptors() -> Vec<ShapeDescriptor>"
assert_file_contains "$TMPDIR/out-rust/api/shapes.rs" "pub fn shape_descriptors() -> Vec<ShapeDescriptor>"
assert_file_contains "$TMPDIR/out-rust/api/shapes.rs" "pub use shape_start_order_processing_request::*;"
assert_file_contains "$TMPDIR/out-rust/api/shapes/start_order_processing_request.rs" "pub struct StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-rust/api/shapes/start_order_processing_request.rs" "pub tenant_id: String"
assert_file_contains "$TMPDIR/out-rust/api/shapes/start_order_processing_request.rs" "START_ORDER_PROCESSING_REQUEST_SHAPE_NAME"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ValueDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/core.rs" "pub fn value_descriptors() -> Vec<ValueDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EnumDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/core.rs" "pub fn enum_descriptors() -> Vec<EnumDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EventDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/events.rs" "pub fn event_descriptors() -> Vec<EventDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/events.rs" "pub struct EventEnvelope"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/events.rs" "pub fn make_order_accepted_event"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn missing_external_system_metadata_mapping_sources"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn source_value"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct DefaultExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemClient"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn build_external_system_call_request"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn call_external_system"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn external_system_metadata_key"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn external_system_metadata_mapping_plan"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub tenant_field: Option<String>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub key_fields: Vec<String>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "tenant_field: Some(\"tenant_id\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "source: \"metadata.base_url\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "target: \"client.base_url\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/external_system.rs" "pub trait ExternalSystemMetadataResolver"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn external_system_metadata_lookup"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn external_system_metadata_lookup_by_name"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn resolve_external_system_metadata_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn resolve_external_system_metadata_by_name_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "key_complete()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "pub fn external_system_descriptors() -> Vec<ExternalSystemDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct ApiDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub use crate::descriptor_types::{ApiDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_descriptors() -> Vec<ApiDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct ApiServerDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiServerDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_server_descriptors() -> Vec<ApiServerDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct ApiRequestContext"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct ApiResponse"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiRouteDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiRequestContext"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct ApiResponse"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ApiHandler"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait ExternalSystemOperatorMetadataApiHandler"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn api_route_descriptors() -> Vec<ApiRouteDescriptor>"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/catalog.rs" "name: \"OrderApi\".to_string()"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/catalog.rs" "serves: vec![\"StartOrderProcessing\".to_string()]"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "name: \"OrderApi.StartOrderProcessing\".to_string()"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "server_name: \"OrderApi\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct WorkerDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/types.rs" "pub struct WorkerContext"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct WorkerDescriptor"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct WorkerContext"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub trait Worker"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn worker_descriptors() -> Vec<WorkerDescriptor>"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn worker_contexts() -> Vec<WorkerContext>"
assert_file_contains "$TMPDIR/out-rust/worker/descriptors/catalog.rs" "pub fn worker_descriptors() -> Vec<WorkerDescriptor>"
assert_file_contains "$TMPDIR/out-rust/worker/descriptors/catalog.rs" "use crate::descriptor_types::{WorkerContext, WorkerDescriptor}"
assert_file_contains "$TMPDIR/out-rust/worker/descriptors/catalog.rs" "pub fn worker_contexts() -> Vec<WorkerContext>"
assert_file_contains "$TMPDIR/out-rust/worker/descriptors/order_worker.rs" "use crate::descriptor_types::{WorkerContext, WorkerDescriptor}"
assert_file_contains "$TMPDIR/out-rust/worker/descriptors/order_worker.rs" "name: \"OrderWorker\".to_string()"
assert_file_contains "$TMPDIR/out-rust/worker/descriptors/order_worker.rs" "polls: Some(\"EmailDispatch.SendConfirmation\".to_string())"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct PolicyDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/policies.rs" "pub fn policy_descriptors() -> Vec<PolicyDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct EntityInvariantDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/entity_repository.rs" "pub trait EntityRepository"
assert_file_contains "$TMPDIR/out-rust/common/entity_repository.rs" "pub struct DefaultEntityRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/account/persistence.rs" "pub trait AccountRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/account/persistence.rs" "pub struct DefaultAccountRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "pub trait OrderRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "pub struct DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-rust/common/entities/account/constants.rs" "ACCOUNT_ENTITY_NAME"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "ORDER_FIELD_TENANT_ID"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "ORDER_INDEX_BY_TENANT_STATUS"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "ORDER_INDEX_BY_TENANT_ORDER"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "FieldDescriptor { name: ORDER_FIELD_TENANT_ID.to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "ORDER_INDEX_BY_TENANT_STATUS.to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "ORDER_INDEX_BY_TENANT_ORDER.to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "create_tx"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "list_by_index_tx"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "list_by_tenant_status_tx"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/persistence.rs" "list_by_tenant_order_tx"
assert_file_contains "$TMPDIR/out-rust/common/entity_repository.rs" "pub fn entity_lookup_from_document"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn entity_descriptors() -> Vec<EntityDescriptor>"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub fn collection_descriptors() -> Vec<CollectionDescriptor>"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "IndexDescriptor"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "pub fn queue_definitions() -> Vec<QueueDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "pub fn lease_definitions() -> Vec<LeaseDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "pub fn workflow_definitions() -> Vec<WorkflowDefinition>"
assert_file_exists "$TMPDIR/out-rust/common/workflows/order_processing.rs"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "EmailDispatch"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "OrderReconciler"
assert_file_contains "$TMPDIR/out-rust/common/workflows/order_processing.rs" "workflow_version: 2"
assert_file_contains "$TMPDIR/out-rust/common/workflows/order_processing.rs" "validate_order"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime.rs" "NewScheduler"
assert_file_contains "$TMPDIR/out-rust/api/shapes.rs" "shape_start_order_processing_request::start_order_processing_request_shape_descriptors()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/core.rs" "OrderAmount"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/core.rs" "OrderStatus"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/events.rs" "OrderAccepted"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/external_systems.rs" "Stripe"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "path: Some(\"/v1/tenants/{tenantId}/orders/{order_id}/start\".to_string())"
assert_file_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "crate::api_shapes::shape_start_order_processing_request::START_ORDER_PROCESSING_REQUEST_SHAPE_NAME"
assert_file_not_contains "$TMPDIR/out-rust/api/descriptors/start_order_processing.rs" "common_descriptors"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/policies.rs" "OrderAccess"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct LogDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/observability.rs" "pub fn log_definitions() -> Vec<LogDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/observability.rs" "LogLevel::Info"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/observability.rs" "event_name: \"workflow.launch.decision\".to_string()"
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "pub struct MetricDefinition"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/observability.rs" "pub fn metric_definitions() -> Vec<MetricDefinition>"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/observability.rs" "MetricKind::Counter"
assert_file_contains "$TMPDIR/out-rust/common/runtime_registration.rs" "pub fn ensure_system_collections"
assert_file_contains "$TMPDIR/out-rust/common/runtime_registration.rs" "crate::entity_order::schema::order_collection_descriptor()"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime/feature_flags.rs" "pub fn register_feature_flag_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime/queues.rs" "pub fn register_queue_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime/leases.rs" "pub fn register_lease_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/common/runtime_registration.rs" "pub fn register_runtime_catalog_tx"
assert_file_contains "$TMPDIR/out-rust/common/runtime_registration.rs" "pub fn register_runtime_catalog"
assert_file_contains "$TMPDIR/out-rust/common/runtime_registration.rs" "pub fn bootstrap_runtime_catalog"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime/observability.rs" "pub fn register_observability_catalog_tx"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/runtime/workflows.rs" "pub fn register_workflow_definitions_tx"
assert_file_contains "$TMPDIR/out-rust/api/api_application.rs" "pub fn bootstrap(&self)"
assert_file_contains "$TMPDIR/out-rust/worker/worker_runtime.rs" "pub fn bootstrap(&self)"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/observability.rs" "backend_name: \"workflow_launch_attempts_total\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/constants.rs" "ORDER_RELATION_ACCOUNT_ID_RELATION_KIND: &str = \"composition\""
assert_file_not_contains "$TMPDIR/out-rust/common/descriptors.rs" "name: \"valid_status\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "name: ORDER_INDEX_BY_TENANT_STATUS.to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "unique: true"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/schema.rs" "ORDER_STATE_FAILED_GC_AFTER: &str = \"P30D\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/schema.rs" "ORDER_STATE_FAILED_GC_MODE: &str = \"tombstone\""
assert_file_contains "$TMPDIR/out-rust/api/shapes/start_order_processing_request.rs" "field_type: FieldType::String"
assert_file_contains "$TMPDIR/out-rust/common/descriptors/core.rs" "value_type: \"decimal\".to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "field_type: FieldType::Timestamp"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "field_type: FieldType::Optional"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/constants.rs" "pub const ORDER_FIELD_STATUS_TYPE_NAME: &str = \"string\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/constants.rs" "pub const ORDER_FIELD_RETRY_COUNT_TYPE_NAME: &str = \"int?\""
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "type_name: ORDER_FIELD_STATUS_TYPE_NAME.to_string()"
assert_file_contains "$TMPDIR/out-rust/common/entities/order/model.rs" "type_name: ORDER_FIELD_RETRY_COUNT_TYPE_NAME.to_string()"
mkdir -p "$TMPDIR/out-rust/tests"
cp "$SCRIPT_DIR/metadata_resolver_fixture.rs" "$TMPDIR/out-rust/tests/metadata_resolver_fixture.rs"
cp "$SCRIPT_DIR/memory_backend_fixture.rs" "$TMPDIR/out-rust/tests/memory_backend_fixture.rs"
(cd "$TMPDIR/out-rust" && CARGO_TARGET_DIR="$TMPDIR/rust-target" cargo test)
