.PHONY: test clean help

test:
	go test ./...

clean:
	go clean -testcache

help:
	@echo "StateSpec Go binding targets:"
	@echo "  make test   Run Go binding tests"
	@echo "  make clean  Clean Go test cache"
