#pragma once

#include "statespec/source.hpp"

#include <string>

namespace statespec
{

enum class TokenKind
{
    EndOfFile,
    Identifier,
    StringLiteral,
    IntegerLiteral,
    DecimalLiteral,
    BooleanLiteral,
    DurationLiteral,

    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Less,
    Greater,
    Comma,
    Colon,
    Semicolon,
    Dot,
    Question,
    Arrow,
    Equals,
    EqualEqual,
    BangEqual,
    LessEqual,
    GreaterEqual,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    AndAnd,
    OrOr,

    KeywordStatespec,
    KeywordImport,
    KeywordAs,
    KeywordSystem,
    KeywordNamespace,
    KeywordValue,
    KeywordEnum,
    KeywordShape,
    KeywordExternalSystem,
    KeywordEntity,
    KeywordKey,
    KeywordVersion,
    KeywordFields,
    KeywordStateMachine,
    KeywordState,
    KeywordInitial,
    KeywordTerminal,
    KeywordOwnership,
    KeywordAuthority,
    KeywordSystemOfRecord,
    KeywordLifecycle,
    KeywordControl,
    KeywordRelations,
    KeywordParent,
    KeywordRef,
    KeywordOptional,
    KeywordChildren,
    KeywordInvariants,
    KeywordIndexes,
    KeywordAnnotations,
    KeywordEvent,
    KeywordQueue,
    KeywordMessage,
    KeywordPayload,
    KeywordLease,
    KeywordWorker,
    KeywordApi,
    KeywordBehavior,
    KeywordWorkflow,
    KeywordStep,
    KeywordChildSet,
    KeywordPolicy,
    KeywordWhen,
    KeywordWhere,
    KeywordRequire,
    KeywordSet,
    KeywordEmit,
    KeywordEmits,
    KeywordEnqueue,
    KeywordAcquire,
    KeywordRenew,
    KeywordRelease,
    KeywordStart,
    KeywordLoad,
    KeywordAllocates,
    KeywordReturns,
    KeywordAtomic,
    KeywordForEach,
    KeywordIn,
    KeywordCreate,
    KeywordChild,
    KeywordObserve,
    KeywordMove,
    KeywordFrom,
    KeywordTo,
    KeywordTransitionTo,
    KeywordComplete,
    KeywordFail,
    KeywordReserve,
    KeywordMaterialize,
    KeywordReconcile,
    KeywordAllow,
    KeywordDeny,
    KeywordQuota,
    KeywordAudit,
    KeywordTenant,
    KeywordScopedBy,
    KeywordMethod,
    KeywordPath,
    KeywordInput,
    KeywordOutput,
    KeywordError,
    KeywordAuthz,
    KeywordStarts,
    KeywordEnqueues,
    KeywordPolls,
    KeywordExecutes,
    KeywordSingleton,
    KeywordConcurrency,

    Unknown,
};

struct Token
{
    TokenKind kind = TokenKind::Unknown;
    std::string lexeme;
    SourceRange range;
};

std::string token_kind_name(TokenKind kind);

} // namespace statespec
