#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

run_expect_status 0 "$CLI" generate bindings --lang cpp "$SPEC" --out "$TMPDIR/out-cpp"
assert_output_contains "generated $TMPDIR/out-cpp/common/backend.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/json.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/backend.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/external_system.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/feature_flag.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/lease.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/log.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/metric.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/queue.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/workflow.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/memory/backend.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/memory/transaction.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_core.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_feature_flags.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_queues.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_leases.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_workflows.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_observability.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_logs.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/codec_metrics.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/feature_flag_store.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/queue_store.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/lease_store.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/workflow_store.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/log_sink.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/metric_sink.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/entity_gc_descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/entity_gc_repository.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/runtime/entity_gc_workers.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/core.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/shapes.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/apis.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/workers.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/runtime.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/entities/account.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/descriptors/entities/order.hpp"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "#include \"descriptors/core.hpp\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "#include \"descriptors/entities/account.hpp\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "#include \"descriptors/entities/order.hpp\""
assert_file_exists "$TMPDIR/out-cpp/Makefile"
assert_file_exists "$TMPDIR/out-cpp/api/api_descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_codecs.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_handlers.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_dispatcher.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_process.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_server.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_transport.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_routes.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/external_system_operator_metadata_api.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_contexts.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_registry.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_application.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_process.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/workflow_runner.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_queues.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_leases.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_workflows.hpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "CXX ?= clang++"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "CXXFLAGS ?= -std=c++20 -Wall -Wextra -Wpedantic -I. -Icommon"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "help:"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "Default target: all -> check"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "Use make build-worker to compile worker/main.cpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "check-common"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "check-api"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "check-worker"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "api/api_descriptors.hpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "worker/worker_descriptors.hpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "worker/worker_workflows.hpp"
assert_file_contains "$TMPDIR/out-cpp/api/api_descriptors.hpp" "namespace statespec_generated::api"
assert_file_contains "$TMPDIR/out-cpp/api/api_descriptors.hpp" "api_descriptors"
assert_file_contains "$TMPDIR/out-cpp/api/api_handlers.hpp" "class IApiOperationHandler"
assert_file_contains "$TMPDIR/out-cpp/api/api_handlers.hpp" "handle_start_order_processing"
assert_file_contains "$TMPDIR/out-cpp/api/api_codecs.hpp" "decode_start_order_processing_request"
assert_file_contains "$TMPDIR/out-cpp/api/api_codecs.hpp" "encode_start_order_processing_response"
assert_file_contains "$TMPDIR/out-cpp/api/api_handler_registry.hpp" "decode_start_order_processing_request"
assert_file_contains "$TMPDIR/out-cpp/api/api_handler_registry.hpp" "encode_start_order_processing_response"
assert_file_not_contains "$TMPDIR/out-cpp/api/api_handler_registry.hpp" "handler_not_implemented"
assert_file_contains "$TMPDIR/out-cpp/api/api_dispatcher.hpp" "find_api_route"
assert_file_contains "$TMPDIR/out-cpp/api/api_dispatcher.hpp" "dispatch_api_route"
assert_file_not_contains "$TMPDIR/out-cpp/api/api_dispatcher.hpp" "dispatch_api_operation_route"
assert_file_contains "$TMPDIR/out-cpp/api/api_server.hpp" "find_api_server"
assert_file_contains "$TMPDIR/out-cpp/api/api_server.hpp" "class ApiServer"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "class ApiProcess"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "void bootstrap()"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "std::thread worker_"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "std::optional<int> status_"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "int start()"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "int join()"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "bool running() const"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "bool entity_gc_enabled = true"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "using EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "void add_entity_gc_worker"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "start_entity_gc_workers()"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "class IApiTransport"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "server.handle(route_name, context)"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "class LocalBlockingApiTransport"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "int run() override"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "virtual void request_stop() = 0"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "void request_stop() override"
assert_file_contains "$TMPDIR/out-cpp/api/api_transport.hpp" "stop_requested_.wait"
assert_file_contains "$TMPDIR/out-cpp/api/api_process.hpp" "transport_.request_stop()"
assert_file_contains "$TMPDIR/out-cpp/api/main.cpp" "LocalBlockingApiTransport transport"
assert_file_contains "$TMPDIR/out-cpp/api/api_routes.hpp" "api_route_descriptors"
assert_file_contains "$TMPDIR/out-cpp/api/external_system_operator_metadata_api.hpp" "IExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-cpp/api/api_application.hpp" "statespec::backend::IBackend& backend_"
assert_file_not_contains "$TMPDIR/out-cpp/api/api_application.hpp" "common/memory/backend.hpp"
assert_file_contains "$TMPDIR/out-cpp/api/main.cpp" "../common/memory/backend.hpp"
assert_file_contains "$TMPDIR/out-cpp/api/main.cpp" "ApiProcessConfig::all_servers"
assert_file_contains "$TMPDIR/out-cpp/api/main.cpp" "std::signal(SIGINT"
assert_file_contains "$TMPDIR/out-cpp/api/main.cpp" "process.start()"
assert_file_contains "$TMPDIR/out-cpp/api/main.cpp" "process.join()"
assert_file_not_contains "$TMPDIR/out-cpp/api/main.cpp" "ApiApplication app"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_descriptors.hpp" "worker_descriptors"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_contexts.hpp" "worker_contexts"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_registry.hpp" "find_worker_descriptor"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_application.hpp" "class WorkerApplication"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "class WorkerProcess"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "struct WorkerProcessConfig"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "int start()"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "int join()"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "bool running() const"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "void request_stop()"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_process.hpp" "start_worker_loops"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "class IWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "class DefaultWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "handle_order_processing_validate_order"
assert_file_not_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "virtual void handle(const WorkflowStepHandlerContext"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "workflow_step_handler_keys"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_runner.hpp" "class WorkflowRunner"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_runner.hpp" "handler_.handle_order_processing_validate_order"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_runner.hpp" "keep_alive_step"
assert_file_not_exists "$TMPDIR/out-cpp/worker/worker_handlers.hpp"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "statespec::backend::IBackend& backend_"
assert_file_not_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "common/memory/backend.hpp"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "struct WorkerRuntimeConfig"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "bool entity_gc_enabled = true"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "using EntityGcWorkerTask"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "void start_entity_gc_workers"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "void request_stop()"
assert_file_contains "$TMPDIR/out-cpp/worker/main.cpp" "../common/memory/backend.hpp"
assert_file_contains "$TMPDIR/out-cpp/worker/main.cpp" "DefaultWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-cpp/worker/main.cpp" "WorkerProcess"
assert_file_contains "$TMPDIR/out-cpp/worker/main.cpp" "std::signal(SIGINT"
assert_file_contains "$TMPDIR/out-cpp/worker/main.cpp" "process.start()"
assert_file_contains "$TMPDIR/out-cpp/worker/main.cpp" "process.join()"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_queues.hpp" "queue_definitions"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_leases.hpp" "lease_definitions"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_workflows.hpp" "workflow_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/backend.hpp" "enum class FieldType"
assert_file_contains "$TMPDIR/out-cpp/common/backend.hpp" "FieldType type"
assert_file_contains "$TMPDIR/out-cpp/common/backend.hpp" "std::string type_name"
assert_file_contains "$TMPDIR/out-cpp/common/workflow.hpp" "KeepAliveWorkflowStepRequest"
assert_file_contains "$TMPDIR/out-cpp/common/workflow.hpp" "keep_alive_stepTx"
assert_file_contains "$TMPDIR/out-cpp/common/memory/backend.hpp" "class InMemoryBackend"
assert_file_contains "$TMPDIR/out-cpp/common/memory/transaction.hpp" "class InMemoryTransaction"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/codec_feature_flags.hpp" "feature_flag_definition_to_json"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/codec_logs.hpp" "log_definition_to_json"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/codec_metrics.hpp" "metric_definition_to_json"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/feature_flag_store.hpp" "class RuntimeFeatureFlagStore"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/queue_store.hpp" "class RuntimeQueueStore"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/lease_store.hpp" "class RuntimeLeaseStore"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/workflow_store.hpp" "class RuntimeWorkflowStore"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/log_sink.hpp" "class RuntimeLogSink"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/metric_sink.hpp" "class RuntimeMetricSink"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/entity_gc_descriptors.hpp" "EntityGcDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/entity_gc_descriptors.hpp" "::statespec_generated::kOrderEntityName"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/entity_gc_descriptors.hpp" "::statespec_generated::kOrderStatusFailed"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/entity_gc_repository.hpp" "class IEntityGcRepository"
assert_file_contains "$TMPDIR/out-cpp/common/runtime/entity_gc_workers.hpp" "class EntityGcWorker"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "feature_flag_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ShapeDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "shape_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "statespec::backend::FieldType::String"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "statespec::backend::FieldType::Named"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "statespec::backend::FieldType::Timestamp"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "statespec::backend::FieldType::Optional"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderFieldStatusTypeName = \"string\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderFieldRetryCountTypeName = \"int?\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderFieldStatus, statespec::backend::FieldType::String, kOrderFieldStatusTypeName"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderFieldRetryCount, statespec::backend::FieldType::Optional, kOrderFieldRetryCountTypeName"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "struct StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "std::string tenant_id"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ValueDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "value_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EnumDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "enum_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EventDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "event_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "struct EventEnvelope"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "make_order_accepted_event"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemMetadataMappingDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "IExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "missing_external_system_metadata_mapping_sources"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "source_value"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "IExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "DefaultExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "DefaultExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "external_system_metadata_key"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "IExternalSystemClient"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ExternalSystemCallRequest"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "build_external_system_call_request"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "call_external_system"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "external_system_metadata_mapping_plan"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "std::optional<std::string> tenant_field"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "std::vector<std::string> key_fields"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"metadata.base_url\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"client.base_url\""
assert_file_contains "$TMPDIR/out-cpp/common/external_system.hpp" "IExternalSystemMetadataResolver"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "external_system_metadata_lookup"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "resolve_external_system_metadataTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "key_complete()"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "external_system_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ApiDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "api_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "api_server_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ApiRequestContext"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ApiResponse"
assert_file_not_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class IApiHandler"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class IExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "api_route_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"OrderApi\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"OrderApi.StartOrderProcessing\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "WorkerDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "WorkerContext"
assert_file_not_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class IWorker"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "worker_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "worker_contexts"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"OrderWorker\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"EmailDispatch.SendConfirmation\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "PolicyDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "policy_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EntityInvariantDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class IEntityRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class DefaultEntityRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class IAccountRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class DefaultAccountRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class IOrderRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "class DefaultOrderRepository"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kAccountEntityName"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderFieldTenantId"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderIndexByTenantStatus"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderIndexByTenantOrder"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "FieldDescriptor{kOrderFieldTenantId"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "listByIndexTx(tx, kOrderIndexByTenantStatus"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "listByIndexTx(tx, kOrderIndexByTenantOrder"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "createTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "listByIndexTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "listByTenantStatusTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "listByTenantOrderTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "entity_lookup_from_document"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "entity_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "CollectionDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "IndexDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "queue_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "lease_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "workflow_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "EmailDispatch"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "OrderReconciler"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "OrderProcessing"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "validate_order"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "NewScheduler"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "MaxPendingOrders"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "OrderAmount"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "OrderStatus"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "OrderAccepted"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "Stripe"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "/v1/tenants/{tenantId}/orders/{order_id}/start"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "OrderAccess"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "struct LogDefinition"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "log_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "WorkflowLaunchDecision"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "workflow.launch.decision"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "struct MetricDefinition"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "metric_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "ensure_system_collections"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_feature_flag_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_queue_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_lease_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_runtime_catalogTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_runtime_catalog("
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "bootstrap_runtime_catalog"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_observability_catalogTx"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "register_workflow_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/api/api_application.hpp" "void bootstrap()"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_runtime.hpp" "void bootstrap()"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "workflow_launch_attempts_total"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"composition\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"account_id\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"valid_status\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderIndexByTenantStatus"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "kOrderIndexByTenantOrder"
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"P30D\""
assert_file_contains "$TMPDIR/out-cpp/common/descriptors.hpp" "\"tombstone\""

(cd "$TMPDIR/out-cpp" && make check)

cp "$SCRIPT_DIR/metadata_resolver_fixture.cpp" "$TMPDIR/out-cpp/metadata_resolver_fixture.cpp"
${CXX:-c++} -std=c++20 -I"$TMPDIR/out-cpp" "$TMPDIR/out-cpp/metadata_resolver_fixture.cpp" -o "$TMPDIR/out-cpp/metadata_resolver_fixture"
"$TMPDIR/out-cpp/metadata_resolver_fixture"
cp "$SCRIPT_DIR/memory_backend_fixture.cpp" "$TMPDIR/out-cpp/memory_backend_fixture.cpp"
${CXX:-c++} -std=c++20 -I"$TMPDIR/out-cpp" -I"$TMPDIR/out-cpp/common" "$TMPDIR/out-cpp/memory_backend_fixture.cpp" -o "$TMPDIR/out-cpp/memory_backend_fixture"
"$TMPDIR/out-cpp/memory_backend_fixture"
