#!/bin/sh
set -eu

CLI="$1"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TESTS_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
. "$TESTS_DIR/cli/common.sh"

SPEC="$TESTS_DIR/fixtures/bindings-full.sspec"

run_expect_status 0 "$CLI" generate bindings --lang cpp "$SPEC" --out "$TMPDIR/out-cpp"
assert_output_contains "generated $TMPDIR/out-cpp/common/backend.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/json.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/backend.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/external_system.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/feature_flag.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/lease.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/log.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/metric.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/queue.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/workflow.hpp"
assert_file_exists "$TMPDIR/out-cpp/common/system_descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/Makefile"
assert_file_exists "$TMPDIR/out-cpp/api/api_descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_handlers.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_dispatcher.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_server.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/api_routes.hpp"
assert_file_exists "$TMPDIR/out-cpp/api/external_system_operator_metadata_api.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_descriptors.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_contexts.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_registry.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_application.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/workflow_runner.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_handlers.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_queues.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_leases.hpp"
assert_file_exists "$TMPDIR/out-cpp/worker/worker_workflows.hpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "CXX ?= clang++"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "CXXFLAGS ?= -std=c++20 -Wall -Wextra -Wpedantic -I. -Icommon"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "check-common"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "check-api"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "check-worker"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "build-api"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "build-worker"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "package-api"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "package-worker"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "api/api_descriptors.hpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "worker/worker_descriptors.hpp"
assert_file_contains "$TMPDIR/out-cpp/Makefile" "worker/worker_workflows.hpp"
assert_file_contains "$TMPDIR/out-cpp/api/api_descriptors.hpp" "namespace statespec_generated::api"
assert_file_contains "$TMPDIR/out-cpp/api/api_descriptors.hpp" "api_descriptors"
assert_file_contains "$TMPDIR/out-cpp/api/api_handlers.hpp" "using IApiHandler"
assert_file_contains "$TMPDIR/out-cpp/api/api_dispatcher.hpp" "find_api_route"
assert_file_contains "$TMPDIR/out-cpp/api/api_dispatcher.hpp" "dispatch_api_route"
assert_file_contains "$TMPDIR/out-cpp/api/api_server.hpp" "find_api_server"
assert_file_contains "$TMPDIR/out-cpp/api/api_server.hpp" "class ApiServer"
assert_file_contains "$TMPDIR/out-cpp/api/api_routes.hpp" "api_route_descriptors"
assert_file_contains "$TMPDIR/out-cpp/api/external_system_operator_metadata_api.hpp" "IExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_descriptors.hpp" "worker_descriptors"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_contexts.hpp" "worker_contexts"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_registry.hpp" "find_worker_descriptor"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_application.hpp" "class WorkerApplication"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "class IWorkflowStepHandler"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_step_handlers.hpp" "workflow_step_handler_keys"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_runner.hpp" "class WorkflowRunner"
assert_file_contains "$TMPDIR/out-cpp/worker/workflow_runner.hpp" "keep_alive_step"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_handlers.hpp" "using IWorker"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_queues.hpp" "queue_definitions"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_leases.hpp" "lease_definitions"
assert_file_contains "$TMPDIR/out-cpp/worker/worker_workflows.hpp" "workflow_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/backend.hpp" "enum class FieldType"
assert_file_contains "$TMPDIR/out-cpp/common/backend.hpp" "FieldType type"
assert_file_contains "$TMPDIR/out-cpp/common/backend.hpp" "std::string type_name"
assert_file_contains "$TMPDIR/out-cpp/common/workflow.hpp" "KeepAliveWorkflowStepRequest"
assert_file_contains "$TMPDIR/out-cpp/common/workflow.hpp" "keep_alive_stepTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "FeatureFlagDefinition"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "feature_flag_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ShapeDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "shape_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "statespec::backend::FieldType::String"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "statespec::backend::FieldType::Named"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "statespec::backend::FieldType::Timestamp"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "statespec::backend::FieldType::Optional"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"OrderStatus\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"int?\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "struct StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "std::string tenant_id"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ValueDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "value_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EnumDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "enum_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EventDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "event_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "struct EventEnvelope"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "make_order_accepted_event"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemMetadataDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemMetadataMappingDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemMetadataMappingPlan"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemOperatorMetadataUpsertRequest"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "IExternalSystemOperatorMetadataRepository"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemMetadataMappingInputs"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ExternalSystemMetadataMissingMappingSource"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "missing_external_system_metadata_mapping_sources"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "source_value"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "IExternalSystemMetadataMappingApplicator"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "external_system_metadata_mapping_plan"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "std::optional<std::string> tenant_field"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "std::vector<std::string> key_fields"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"metadata.base_url\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"client.base_url\""
assert_file_contains "$TMPDIR/out-cpp/common/external_system.hpp" "IExternalSystemMetadataResolver"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "external_system_metadata_lookup"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "resolve_external_system_metadataTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "key_complete()"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "external_system_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ApiDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "api_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ApiServerDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "api_server_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ApiRouteDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ApiRequestContext"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ApiResponse"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "class IApiHandler"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "class IExternalSystemOperatorMetadataApiHandler"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "api_route_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"OrderApi\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"OrderApi.StartOrderProcessing\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "WorkerDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "WorkerContext"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "class IWorker"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "worker_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "worker_contexts"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"OrderWorker\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"EmailDispatch.SendConfirmation\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "PolicyDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "policy_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "GarbageCollectionPolicy"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EntityStateDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EntityOwnershipDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EntityRelationDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EntityChildDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EntityInvariantDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "entity_descriptors"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "CollectionDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "IndexDescriptor"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "queue_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "lease_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "workflow_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "EmailDispatch"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "OrderReconciler"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "OrderProcessing"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "validate_order"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "NewScheduler"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "MaxPendingOrders"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "StartOrderProcessingRequest"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "OrderAmount"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "OrderStatus"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "OrderAccepted"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "Stripe"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "StartOrderProcessing"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "/v1/tenants/{tenantId}/orders/{order_id}/start"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "OrderAccess"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "struct LogDefinition"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "log_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "WorkflowLaunchDecision"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "workflow.launch.decision"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "struct MetricDefinition"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "metric_definitions"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "ensure_system_collections"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "register_feature_flag_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "register_queue_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "register_lease_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "register_runtime_catalogTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "register_observability_catalogTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "register_workflow_definitionsTx"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "workflow_launch_attempts_total"
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"composition\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"account_id\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"valid_status\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"by_tenant_status\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"by_tenant_order\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"P30D\""
assert_file_contains "$TMPDIR/out-cpp/common/system_descriptors.hpp" "\"tombstone\""

(cd "$TMPDIR/out-cpp" && make check)

cp "$SCRIPT_DIR/metadata_resolver_fixture.cpp" "$TMPDIR/out-cpp/metadata_resolver_fixture.cpp"
${CXX:-c++} -std=c++20 -I"$TMPDIR/out-cpp" "$TMPDIR/out-cpp/metadata_resolver_fixture.cpp" -o "$TMPDIR/out-cpp/metadata_resolver_fixture"
"$TMPDIR/out-cpp/metadata_resolver_fixture"
