#pragma once

#include "statespec/generator.hpp"

#include <algorithm>
#include <cctype>
#include <optional>
#include <ostream>
#include <sstream>
#include <string>

namespace statespec::generator_backend
{

inline std::string join_path(
    const std::string& left,
    const std::string& right
)
{
    if (left.empty())
    {
        return right;
    }
    return left.back() == '/' ? left + right : left + "/" + right;
}

inline std::string output_root(
    const GenerateDecl& declaration,
    const GenerationOptions& options
)
{
    if (options.out_override.has_value())
    {
        return *options.out_override;
    }
    if (declaration.out.has_value())
    {
        return *declaration.out;
    }
    return "generated/" + declaration.target;
}

inline std::string bool_text(bool value)
{
    return value ? "true" : "false";
}

inline std::string optional_or_empty(const std::optional<std::string>& value)
{
    return value.value_or("");
}

inline std::string optional_bool_or_empty(const std::optional<bool>& value)
{
    return value.has_value() ? bool_text(*value) : "";
}

inline bool is_optional_type(const std::string& type)
{
    return !type.empty() && type.back() == '?';
}

inline std::string strip_optional_suffix(const std::string& type)
{
    return is_optional_type(type) ? type.substr(0, type.size() - 1) : type;
}

inline std::string to_lower(std::string value)
{
    std::transform(
        value.begin(), value.end(), value.begin(),
        [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); }
    );
    return value;
}

inline std::string cpp_type_for_statespec_type(const std::string& type)
{
    const auto optional = is_optional_type(type);
    const auto base = strip_optional_suffix(type);

    std::string cpp_type;
    if (base == "string" || base == "uuid" || base == "json")
    {
        cpp_type = "std::string";
    }
    else if (base == "bool")
    {
        cpp_type = "bool";
    }
    else if (base == "int" || base == "int32")
    {
        cpp_type = "std::int32_t";
    }
    else if (base == "int64" || base == "long")
    {
        cpp_type = "std::int64_t";
    }
    else if (base == "double" || base == "decimal")
    {
        cpp_type = "double";
    }
    else if (base == "timestamp")
    {
        cpp_type = "std::chrono::system_clock::time_point";
    }
    else if (base == "duration")
    {
        cpp_type = "std::chrono::seconds";
    }
    else
    {
        cpp_type = base;
    }

    return optional ? "std::optional<" + cpp_type + ">" : cpp_type;
}

inline void append_header(
    std::ostream& out,
    const SystemDecl& system,
    const std::string& target
)
{
    out << "# Generated by StateSpec\n";
    out << "# target: " << target << "\n";
    out << "# system: " << system.name << "\n\n";
}

void generate_openapi(
    const SystemDecl& system,
    const GenerateDecl& declaration,
    const GenerationOptions& options,
    GenerationResult& result
);

void generate_scaffold(
    const SystemDecl& system,
    const GenerateDecl& declaration,
    const GenerationOptions& options,
    GenerationResult& result
);

} // namespace statespec::generator_backend
