#include "statespec/generator.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>
#include <unordered_set>

namespace statespec
{

namespace
{

std::string default_out_for_target(const std::string& target)
{
    return "generated/" + target;
}

std::string output_root(
    const GenerateDecl& declaration,
    const GenerationOptions& options
)
{
    if (options.out_override.has_value())
    {
        return *options.out_override;
    }
    if (declaration.out.has_value())
    {
        return *declaration.out;
    }
    return default_out_for_target(declaration.target);
}

std::string join_path(
    const std::string& left,
    const std::string& right
)
{
    if (left.empty())
    {
        return right;
    }
    if (left.back() == '/')
    {
        return left + right;
    }
    return left + "/" + right;
}

std::string bool_text(bool value)
{
    return value ? "true" : "false";
}

std::string optional_or_empty(const std::optional<std::string>& value)
{
    return value.value_or("");
}

std::string strip_optional_suffix(const std::string& type)
{
    if (!type.empty() && type.back() == '?')
    {
        return type.substr(0, type.size() - 1);
    }
    return type;
}

bool is_optional_type(const std::string& type)
{
    return !type.empty() && type.back() == '?';
}

std::string to_lower(std::string value)
{
    std::transform(
        value.begin(), value.end(), value.begin(), [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); }
    );
    return value;
}

std::string cpp_type_for_statespec_type(const std::string& type)
{
    const auto optional = is_optional_type(type);
    const auto base = strip_optional_suffix(type);

    std::string cpp_type;
    if (base == "string" || base == "uuid" || base == "json")
    {
        cpp_type = "std::string";
    }
    else if (base == "bool")
    {
        cpp_type = "bool";
    }
    else if (base == "int" || base == "int32")
    {
        cpp_type = "std::int32_t";
    }
    else if (base == "int64" || base == "long")
    {
        cpp_type = "std::int64_t";
    }
    else if (base == "double" || base == "decimal")
    {
        cpp_type = "double";
    }
    else if (base == "timestamp")
    {
        cpp_type = "std::chrono::system_clock::time_point";
    }
    else if (base == "duration")
    {
        cpp_type = "std::chrono::seconds";
    }
    else
    {
        cpp_type = base;
    }

    if (optional)
    {
        return "std::optional<" + cpp_type + ">";
    }
    return cpp_type;
}

void append_header(
    std::ostringstream& out,
    const SystemDecl& system,
    const std::string& target
)
{
    out << "# Generated by StateSpec\n";
    out << "# target: " << target << "\n";
    out << "# system: " << system.name << "\n\n";
}

std::string generate_mt_manifest(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "entities:\n";
    for (const auto& entity : system.entities)
    {
        out << "  - name: " << entity.name << "\n";
        out << "    keys:\n";
        for (const auto& key : entity.key_fields)
        {
            out << "      - " << key << "\n";
        }
        out << "    fields:\n";
        for (const auto& field : entity.fields)
        {
            out << "      - name: " << field.name << "\n";
            out << "        type: " << field.type << "\n";
            out << "        cpp_type: " << cpp_type_for_statespec_type(field.type) << "\n";
            out << "        optional: " << bool_text(is_optional_type(field.type)) << "\n";
        }
        if (entity.state_machine.has_value())
        {
            out << "    state_machine:\n";
            out << "      initial: " << optional_or_empty(entity.state_machine->initial_state) << "\n";
            out << "      terminal:\n";
            for (const auto& state : entity.state_machine->terminal_states)
            {
                out << "        - " << state << "\n";
            }
        }
    }
    return out.str();
}

std::string generate_mt_entities_header(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#pragma once\n\n";
    out << "#include <chrono>\n";
    out << "#include <cstdint>\n";
    out << "#include <optional>\n";
    out << "#include <string>\n";
    out << "#include <string_view>\n\n";
    out << "namespace statespec_generated::mt\n";
    out << "{\n\n";

    out << "struct FieldMetadata\n";
    out << "{\n";
    out << "    std::string_view name;\n";
    out << "    std::string_view statespec_type;\n";
    out << "    std::string_view cpp_type;\n";
    out << "    bool optional;\n";
    out << "};\n\n";

    out << "struct EntityMetadata\n";
    out << "{\n";
    out << "    std::string_view name;\n";
    out << "    const FieldMetadata* fields;\n";
    out << "    std::size_t field_count;\n";
    out << "    const std::string_view* keys;\n";
    out << "    std::size_t key_count;\n";
    out << "};\n\n";

    for (const auto& entity : system.entities)
    {
        out << "struct " << entity.name << "\n";
        out << "{\n";
        for (const auto& field : entity.fields)
        {
            out << "    " << cpp_type_for_statespec_type(field.type) << ' ' << field.name << "{};\n";
        }
        out << "};\n\n";
    }

    out << "const EntityMetadata* entities();\n";
    out << "std::size_t entity_count();\n\n";
    out << "} // namespace statespec_generated::mt\n";
    return out.str();
}

std::string generate_mt_metadata_source(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#include \"mt_entities.hpp\"\n\n";
    out << "#include <array>\n\n";
    out << "namespace statespec_generated::mt\n";
    out << "{\n";
    out << "namespace\n";
    out << "{\n\n";

    for (const auto& entity : system.entities)
    {
        const auto entity_name = to_lower(entity.name);
        out << "constexpr std::array<FieldMetadata, " << entity.fields.size() << "> " << entity_name
            << "_fields{{\n";
        for (const auto& field : entity.fields)
        {
            out << "    FieldMetadata{\"" << field.name << "\", \"" << field.type << "\", \""
                << cpp_type_for_statespec_type(field.type) << "\", " << bool_text(is_optional_type(field.type))
                << "},\n";
        }
        out << "}};\n\n";

        out << "constexpr std::array<std::string_view, " << entity.key_fields.size() << "> " << entity_name
            << "_keys{{\n";
        for (const auto& key : entity.key_fields)
        {
            out << "    \"" << key << "\",\n";
        }
        out << "}};\n\n";
    }

    out << "constexpr std::array<EntityMetadata, " << system.entities.size() << "> all_entities{{\n";
    for (const auto& entity : system.entities)
    {
        const auto entity_name = to_lower(entity.name);
        out << "    EntityMetadata{\"" << entity.name << "\", " << entity_name << "_fields.data(), "
            << entity_name << "_fields.size(), " << entity_name << "_keys.data(), " << entity_name
            << "_keys.size()},\n";
    }
    out << "}};\n\n";

    out << "} // namespace\n\n";
    out << "const EntityMetadata* entities()\n";
    out << "{\n";
    out << "    return all_entities.data();\n";
    out << "}\n\n";
    out << "std::size_t entity_count()\n";
    out << "{\n";
    out << "    return all_entities.size();\n";
    out << "}\n\n";
    out << "} // namespace statespec_generated::mt\n";
    return out.str();
}

std::string generate_mt_state_machine_manifest(const SystemDecl& system)
{
    std::ostringstream out;
    append_header(out, system, "mt-state-machines");
    out << "state_machines:\n";
    for (const auto& entity : system.entities)
    {
        if (!entity.state_machine.has_value())
        {
            continue;
        }
        out << "  - entity: " << entity.name << "\n";
        out << "    initial: " << optional_or_empty(entity.state_machine->initial_state) << "\n";
        out << "    states:\n";
        for (const auto& state : entity.state_machine->states)
        {
            out << "      - " << state.name << "\n";
        }
        out << "    terminal_states:\n";
        for (const auto& state : entity.state_machine->terminal_states)
        {
            out << "      - " << state << "\n";
        }
        out << "    transitions:\n";
        for (const auto& transition : entity.state_machine->transitions)
        {
            out << "      - from: " << transition.from << "\n";
            out << "        to: " << transition.to << "\n";
        }
    }
    return out.str();
}

std::string generate_dl_manifest(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "leases:\n";
    for (const auto& lease : system.leases)
    {
        out << "  - name: " << lease.name << "\n";
        out << "    resource: " << optional_or_empty(lease.resource) << "\n";
        out << "    ttl: " << optional_or_empty(lease.ttl) << "\n";
        out << "    renew_every: " << optional_or_empty(lease.renew_every) << "\n";
        out << "    holder: " << optional_or_empty(lease.holder) << "\n";
        out << "    fencing_token: "
            << (lease.fencing_token.has_value() ? bool_text(*lease.fencing_token) : "") << "\n";
    }
    out << "workers:\n";
    for (const auto& worker : system.workers)
    {
        out << "  - name: " << worker.name << "\n";
        out << "    lease: " << optional_or_empty(worker.lease) << "\n";
        out << "    singleton: "
            << (worker.singleton.has_value() ? bool_text(*worker.singleton) : "") << "\n";
    }
    return out.str();
}

std::string generate_qu_manifest(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "queues:\n";
    for (const auto& queue : system.queues)
    {
        out << "  - name: " << queue.name << "\n";
        out << "    namespace: " << optional_or_empty(queue.namespace_name) << "\n";
        out << "    channel: " << optional_or_empty(queue.channel) << "\n";
        out << "    messages:\n";
        for (const auto& message : queue.messages)
        {
            out << "      - name: " << message.name << "\n";
            out << "        idempotency_key: " << optional_or_empty(message.idempotency_key)
                << "\n";
        }
    }
    return out.str();
}

std::string generate_wf_manifest(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "workflows:\n";
    for (const auto& workflow : system.workflows)
    {
        out << "  - name: " << workflow.name << "\n";
        out << "    version: " << workflow.version.value_or(0) << "\n";
        out << "    start: " << optional_or_empty(workflow.start_step) << "\n";
        out << "    steps:\n";
        for (const auto& step : workflow.steps)
        {
            out << "      - name: " << step.name << "\n";
            out << "        expected_execution_time: "
                << optional_or_empty(step.expected_execution_time) << "\n";
            out << "        max_retries: " << step.max_retries.value_or(0) << "\n";
        }
    }
    return out.str();
}

std::string generate_openapi_stub(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    std::ostringstream out;
    out << "openapi: 3.1.0\n";
    out << "info:\n";
    out << "  title: " << system.name << " API\n";
    out << "  version: 0.1.0\n";
    out << "paths:\n";
    for (const auto& api : system.apis)
    {
        const auto path = api.path.value_or("/");
        const auto method = api.method.value_or("GET");
        out << "  \"" << path << "\":\n";
        out << "    " << method << ":\n";
        out << "      operationId: " << api.name << "\n";
        out << "      responses:\n";
        out << "        \"200\":\n";
        out << "          description: generated stub\n";
    }
    (void)declaration;
    return out.str();
}

std::string manifest_name_for_target(const std::string& target)
{
    if (target == "openapi")
    {
        return "openapi.yaml";
    }
    return target + "-manifest.yaml";
}

std::string content_for_target(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    if (declaration.target == "mt")
    {
        return generate_mt_manifest(system, declaration);
    }
    if (declaration.target == "dl")
    {
        return generate_dl_manifest(system, declaration);
    }
    if (declaration.target == "qu")
    {
        return generate_qu_manifest(system, declaration);
    }
    if (declaration.target == "wf")
    {
        return generate_wf_manifest(system, declaration);
    }
    if (declaration.target == "openapi")
    {
        return generate_openapi_stub(system, declaration);
    }

    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "status: scaffold-only\n";
    return out.str();
}

std::vector<GenerateDecl> selected_declarations(
    const SystemDecl& system,
    const GenerationOptions& options
)
{
    std::vector<GenerateDecl> selected;
    for (const auto& declaration : system.generators)
    {
        if (!options.target_override.has_value() || declaration.target == *options.target_override)
        {
            selected.push_back(declaration);
        }
    }

    if (selected.empty() && options.target_override.has_value())
    {
        GenerateDecl declaration;
        declaration.target = *options.target_override;
        selected.push_back(declaration);
    }

    return selected;
}

} // namespace

GenerationResult Generator::generate(
    const Spec& spec,
    const GenerationOptions& options,
    DiagnosticBag& diagnostics
) const
{
    GenerationResult result;
    if (!spec.system.has_value())
    {
        diagnostics.error(SourceRange{}, "SSPEC5001", "generation requires a system declaration");
        return result;
    }

    const auto& system = *spec.system;
    const auto declarations = selected_declarations(system, options);
    if (declarations.empty())
    {
        diagnostics.error(
            system.range, "SSPEC5002", "generation requires at least one generate declaration"
        );
        return result;
    }

    for (const auto& declaration : declarations)
    {
        generate_target(system, declaration, options, result, diagnostics);
    }

    return result;
}

void Generator::generate_target(
    const SystemDecl& system,
    const GenerateDecl& declaration,
    const GenerationOptions& options,
    GenerationResult& result,
    DiagnosticBag& diagnostics
) const
{
    static const std::unordered_set<std::string> supported_targets{
        "mt", "dl", "qu", "wf", "openapi", "proto", "docs", "tests",
    };

    if (declaration.target == "all")
    {
        for (const auto& target : {"mt", "dl", "qu", "wf", "openapi"})
        {
            GenerateDecl expanded = declaration;
            expanded.target = target;
            generate_target(system, expanded, options, result, diagnostics);
        }
        return;
    }

    if (supported_targets.find(declaration.target) == supported_targets.end())
    {
        diagnostics.error(
            declaration.range, "SSPEC5003",
            "unsupported generate target '" + declaration.target + "'"
        );
        return;
    }

    const auto root = output_root(declaration, options);
    if (declaration.target == "mt")
    {
        result.files.push_back(GeneratedFile{join_path(root, "mt-manifest.yaml"), generate_mt_manifest(system, declaration)});
        result.files.push_back(GeneratedFile{join_path(root, "mt_entities.hpp"), generate_mt_entities_header(system)});
        result.files.push_back(GeneratedFile{join_path(root, "mt_metadata.cpp"), generate_mt_metadata_source(system)});
        result.files.push_back(GeneratedFile{join_path(root, "mt-state-machines.yaml"), generate_mt_state_machine_manifest(system)});
        return;
    }

    const auto path = join_path(root, manifest_name_for_target(declaration.target));
    result.files.push_back(GeneratedFile{path, content_for_target(system, declaration)});
}

} // namespace statespec
