#include "generator_rust_descriptor_areas.hpp"

#include "generator_rust_descriptor_support.hpp"
#include "identifier_case.hpp"

#include <sstream>

namespace statespec
{

std::string generate_rust_descriptor_prelude(
    const IrSystem& system,
    const std::string& external_system_runtime
)
{
    std::ostringstream out;
    out << "use std::collections::BTreeMap;\n";
    out << "use std::time::Duration;\n\n";
    out << "use crate::backend::{Backend, BackendError, BackendResult, CollectionDescriptor, "
           "ConflictKind, FieldDescriptor, FieldType, IndexDescriptor, Transaction, "
           "VersionedRecord};\n";
    out << "use crate::external_system::{ExternalSystemMetadataKeyValue, "
           "ExternalSystemMetadataLookup, ExternalSystemMetadataResolution, "
           "ExternalSystemMetadataResolver};\n";
    out << "use crate::feature_flag::{FeatureFlagDefinition as RuntimeFeatureFlagDefinition, "
           "FeatureFlagScopeKind, FeatureFlagStore, FeatureFlagType, FeatureFlagValue};\n";
    out << "use crate::lease::{LeaseDefinition as RuntimeLeaseDefinition, LeaseDefinitionId, "
           "LeaseStore};\n";
    out << "use crate::json::Json;\n";
    out << "use crate::log::{LogDefinition as RuntimeLogDefinition, LogLevel, LogSink};\n";
    out << "use crate::metric::{MetricDefinition as RuntimeMetricDefinition, MetricKind, "
           "MetricSink};\n";
    out << "use crate::queue::{RegisterQueueDefinitionRequest, QueueDefinition, QueueStore};\n";
    out << "use crate::workflow::{RegisterWorkflowDefinitionRequest, WorkflowDefinition, "
           "WorkflowStepDefinition, WorkflowStore};\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EventEnvelope {\n";
    out << "    pub name: String,\n";
    out << "    pub fields: BTreeMap<String, Json>,\n";
    out << "}\n\n";
    for (const auto& shape : system.shapes)
    {
        out << "#[derive(Debug, Clone)]\n";
        out << "pub struct " << pascal_identifier(shape.name) << " {\n";
        for (const auto& field : shape.fields)
        {
            out << "    pub " << field.name << ": " << rust_shape_type(field.type) << ",\n";
        }
        out << "}\n\n";
    }

    for (const auto& event : system.events)
    {
        out << "pub fn make_" << snake_identifier(event.name) << "_event(\n";
        for (const auto& field : event.fields)
        {
            out << "    " << field.name << ": Json,\n";
        }
        out << ") -> EventEnvelope {\n";
        out << "    let mut fields = BTreeMap::new();\n";
        for (const auto& field : event.fields)
        {
            out << "    fields.insert(" << rust_string(field.name) << ".to_string(), " << field.name
                << ");\n";
        }
        out << "    EventEnvelope { name: " << rust_string(event.name)
            << ".to_string(), fields }\n";
        out << "}\n\n";
    }

    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct LeaseDefinition {\n";
    out << "    pub name: String,\n";
    out << "    pub resource: Option<String>,\n";
    out << "    pub ttl: Duration,\n";
    out << "    pub renew_every: Option<Duration>,\n";
    out << "    pub holder: Option<String>,\n";
    out << "    pub fencing_token: bool,\n";
    out << "    pub max_ttl: Option<Duration>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct FeatureFlagDefinition {\n";
    out << "    pub name: String,\n";
    out << "    pub flag_type: String,\n";
    out << "    pub default_value: String,\n";
    out << "    pub scope: String,\n";
    out << "    pub owner: Option<String>,\n";
    out << "    pub description: Option<String>,\n";
    out << "    pub expires: Option<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ValueDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub value_type: String,\n";
    out << "    pub constraint: Option<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EnumMemberDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub value: Option<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EnumDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub members: Vec<EnumMemberDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EventDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub fields: Vec<FieldDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemPropertyDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub value: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemMetadataMappingDescriptor {\n";
    out << "    pub source: String,\n";
    out << "    pub target: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemMetadataMappingAssignment {\n";
    out << "    pub source: String,\n";
    out << "    pub source_root: String,\n";
    out << "    pub source_field: String,\n";
    out << "    pub target_root: String,\n";
    out << "    pub field: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone, Default)]\n";
    out << "pub struct ExternalSystemMetadataMappingPlan {\n";
    out << "    pub all_mappings: Vec<ExternalSystemMetadataMappingAssignment>,\n";
    out << "    pub client_mappings: Vec<ExternalSystemMetadataMappingAssignment>,\n";
    out << "    pub request_mappings: Vec<ExternalSystemMetadataMappingAssignment>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemMetadataMissingMappingSource {\n";
    out << "    pub source: String,\n";
    out << "    pub source_root: String,\n";
    out << "    pub source_field: String,\n";
    out << "    pub target_root: String,\n";
    out << "    pub field: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone, Default)]\n";
    out << "pub struct ExternalSystemMetadataMappingInputs {\n";
    out << "    pub input: BTreeMap<String, Json>,\n";
    out << "    pub entity: BTreeMap<String, Json>,\n";
    out << "    pub workflow: BTreeMap<String, Json>,\n";
    out << "    pub metadata: BTreeMap<String, Json>,\n";
    out << "}\n\n";
    out << "impl ExternalSystemMetadataMappingInputs {\n";
    out << "    pub fn source_value(&self, source_root: &str, source_field: &str) -> "
           "Option<&Json> {\n";
    out << "        match source_root {\n";
    out << "            \"input\" => self.input.get(source_field),\n";
    out << "            \"entity\" => self.entity.get(source_field),\n";
    out << "            \"workflow\" => self.workflow.get(source_field),\n";
    out << "            \"metadata\" => self.metadata.get(source_field),\n";
    out << "            _ => None,\n";
    out << "        }\n";
    out << "    }\n\n";
    out << "    pub fn assignment_value(\n";
    out << "        &self,\n";
    out << "        assignment: &ExternalSystemMetadataMappingAssignment,\n";
    out << "    ) -> Option<&Json> {\n";
    out << "        self.source_value(&assignment.source_root, &assignment.source_field)\n";
    out << "    }\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone, Default)]\n";
    out << "pub struct ExternalSystemMetadataMappingOutput {\n";
    out << "    pub client_config: BTreeMap<String, Json>,\n";
    out << "    pub request_payload: BTreeMap<String, Json>,\n";
    out << "    pub missing_sources: Vec<ExternalSystemMetadataMissingMappingSource>,\n";
    out << "}\n\n";
    out << "pub fn missing_external_system_metadata_mapping_sources(\n";
    out << "    plan: &ExternalSystemMetadataMappingPlan,\n";
    out << "    inputs: &ExternalSystemMetadataMappingInputs,\n";
    out << ") -> Vec<ExternalSystemMetadataMissingMappingSource> {\n";
    out << "    plan.all_mappings\n";
    out << "        .iter()\n";
    out << "        .filter(|assignment| inputs.assignment_value(assignment).is_none())\n";
    out << "        .map(|assignment| ExternalSystemMetadataMissingMappingSource {\n";
    out << "            source: assignment.source.clone(),\n";
    out << "            source_root: assignment.source_root.clone(),\n";
    out << "            source_field: assignment.source_field.clone(),\n";
    out << "            target_root: assignment.target_root.clone(),\n";
    out << "            field: assignment.field.clone(),\n";
    out << "        })\n";
    out << "        .collect()\n";
    out << "}\n\n";
    out << "pub trait ExternalSystemMetadataMappingApplicator {\n";
    out << "    fn apply_external_system_metadata_mappings(\n";
    out << "        &self,\n";
    out << "        plan: &ExternalSystemMetadataMappingPlan,\n";
    out << "        inputs: &ExternalSystemMetadataMappingInputs,\n";
    out << "    ) -> BackendResult<ExternalSystemMetadataMappingOutput>;\n";
    out << "}\n\n";
    out << external_system_runtime << "\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemMetadataDescriptor {\n";
    out << "    pub entity: String,\n";
    out << "    pub tenant_field: Option<String>,\n";
    out << "    pub profile_field: String,\n";
    out << "    pub key_fields: Vec<String>,\n";
    out << "    pub required_fields: Vec<String>,\n";
    out << "    pub mappings: Vec<ExternalSystemMetadataMappingDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemOperatorMetadataUpsertRequest {\n";
    out << "    pub lookup: ExternalSystemMetadataLookup,\n";
    out << "    pub document: Json,\n";
    out << "    pub expected_version: Option<u64>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemOperatorMetadataGetRequest {\n";
    out << "    pub lookup: ExternalSystemMetadataLookup,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemOperatorMetadataDisableRequest {\n";
    out << "    pub lookup: ExternalSystemMetadataLookup,\n";
    out << "    pub expected_version: Option<u64>,\n";
    out << "    pub disabled_status: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemOperatorMetadataDeleteRequest {\n";
    out << "    pub lookup: ExternalSystemMetadataLookup,\n";
    out << "    pub expected_version: Option<u64>,\n";
    out << "    pub deleted_status: String,\n";
    out << "}\n\n";
    out << "pub trait ExternalSystemOperatorMetadataRepository<B: Backend> {\n";
    out << "    fn upsert_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataUpsertRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>>;\n\n";
    out << "    fn get_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataGetRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>>;\n\n";
    out << "    fn disable_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataDisableRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>>;\n\n";
    out << "    fn delete_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataDeleteRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>>;\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone, Copy, Default)]\n";
    out << "pub struct DefaultExternalSystemMetadataMappingApplicator;\n\n";
    out << "impl ExternalSystemMetadataMappingApplicator for "
           "DefaultExternalSystemMetadataMappingApplicator {\n";
    out << "    fn apply_external_system_metadata_mappings(\n";
    out << "        &self,\n";
    out << "        plan: &ExternalSystemMetadataMappingPlan,\n";
    out << "        inputs: &ExternalSystemMetadataMappingInputs,\n";
    out << "    ) -> BackendResult<ExternalSystemMetadataMappingOutput> {\n";
    out << "        let mut output = ExternalSystemMetadataMappingOutput {\n";
    out << "            client_config: BTreeMap::new(),\n";
    out << "            request_payload: BTreeMap::new(),\n";
    out << "            missing_sources: missing_external_system_metadata_mapping_sources(plan, "
           "inputs),\n";
    out << "        };\n";
    out << "        for assignment in &plan.client_mappings {\n";
    out << "            if let Some(value) = inputs.assignment_value(assignment) {\n";
    out << "                output.client_config.insert(assignment.field.clone(), "
           "value.clone());\n";
    out << "            }\n";
    out << "        }\n";
    out << "        for assignment in &plan.request_mappings {\n";
    out << "            if let Some(value) = inputs.assignment_value(assignment) {\n";
    out << "                output.request_payload.insert(assignment.field.clone(), "
           "value.clone());\n";
    out << "            }\n";
    out << "        }\n";
    out << "        Ok(output)\n";
    out << "    }\n";
    out << "}\n\n";
    out << "pub fn external_system_metadata_key(\n";
    out << "    lookup: &ExternalSystemMetadataLookup,\n";
    out << ") -> Option<String> {\n";
    out << "    if !lookup.key_complete() {\n";
    out << "        return None;\n";
    out << "    }\n";
    out << "    let mut key = String::new();\n";
    out << "    for key_field in &lookup.key_fields {\n";
    out << "        let value = lookup\n";
    out << "            .key_values\n";
    out << "            .iter()\n";
    out << "            .find(|key_value| key_value.field == *key_field)?;\n";
    out << "        key.push_str(key_field);\n";
    out << "        key.push('=');\n";
    out << "        key.push_str(&value.value.canonical_string());\n";
    out << "        key.push('\\n');\n";
    out << "    }\n";
    out << "    Some(key)\n";
    out << "}\n\n";
    out << "pub fn external_system_metadata_document_with_keys(\n";
    out << "    document: &Json,\n";
    out << "    lookup: &ExternalSystemMetadataLookup,\n";
    out << ") -> Json {\n";
    out << "    let mut values = match document {\n";
    out << "        Json::Object(values) => values.clone(),\n";
    out << "        _ => BTreeMap::new(),\n";
    out << "    };\n";
    out << "    for key_value in &lookup.key_values {\n";
    out << "        values.insert(key_value.field.clone(), key_value.value.clone());\n";
    out << "    }\n";
    out << "    Json::Object(values)\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone, Copy, Default)]\n";
    out << "pub struct DefaultExternalSystemOperatorMetadataRepository;\n\n";
    out << "fn assert_external_system_metadata_expected_version(\n";
    out << "    existing: &Option<VersionedRecord>,\n";
    out << "    expected_version: Option<u64>,\n";
    out << ") -> BackendResult<()> {\n";
    out << "    if let Some(expected) = expected_version {\n";
    out << "        if existing.as_ref().map(|record| record.version) != Some(expected) {\n";
    out << "            return Err(BackendError::Conflict {\n";
    out << "                kind: ConflictKind::VersionConflict,\n";
    out << "                message: \"external system metadata version conflict\".to_string(),\n";
    out << "            });\n";
    out << "        }\n";
    out << "    }\n";
    out << "    Ok(())\n";
    out << "}\n\n";
    out << "impl<B: Backend> ExternalSystemOperatorMetadataRepository<B> for "
           "DefaultExternalSystemOperatorMetadataRepository {\n";
    out << "    fn upsert_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataUpsertRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>> {\n";
    out << "        let Some(key) = external_system_metadata_key(&request.lookup) else {\n";
    out << "            return Ok(None);\n";
    out << "        };\n";
    out << "        let existing = tx.get(&request.lookup.metadata_entity, &key)?;\n";
    out << "        assert_external_system_metadata_expected_version(&existing, "
           "request.expected_version)?;\n";
    out << "        tx.put(\n";
    out << "            &request.lookup.metadata_entity,\n";
    out << "            &key,\n";
    out << "            external_system_metadata_document_with_keys(&request.document, "
           "&request.lookup),\n";
    out << "        )?;\n";
    out << "        tx.get(&request.lookup.metadata_entity, &key)\n";
    out << "    }\n\n";
    out << "    fn get_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataGetRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>> {\n";
    out << "        let Some(key) = external_system_metadata_key(&request.lookup) else {\n";
    out << "            return Ok(None);\n";
    out << "        };\n";
    out << "        tx.get(&request.lookup.metadata_entity, &key)\n";
    out << "    }\n\n";
    out << "    fn disable_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataDisableRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>> {\n";
    out << "        self.update_status_tx(\n";
    out << "            tx,\n";
    out << "            &request.lookup,\n";
    out << "            request.expected_version,\n";
    out << "            &request.disabled_status,\n";
    out << "        )\n";
    out << "    }\n\n";
    out << "    fn delete_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        request: &ExternalSystemOperatorMetadataDeleteRequest,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>> {\n";
    out << "        self.update_status_tx(\n";
    out << "            tx,\n";
    out << "            &request.lookup,\n";
    out << "            request.expected_version,\n";
    out << "            &request.deleted_status,\n";
    out << "        )\n";
    out << "    }\n";
    out << "}\n\n";
    out << "impl DefaultExternalSystemOperatorMetadataRepository {\n";
    out << "    fn update_status_tx<T: Transaction>(\n";
    out << "        &self,\n";
    out << "        tx: &mut T,\n";
    out << "        lookup: &ExternalSystemMetadataLookup,\n";
    out << "        expected_version: Option<u64>,\n";
    out << "        status: &str,\n";
    out << "    ) -> BackendResult<Option<VersionedRecord>> {\n";
    out << "        let Some(key) = external_system_metadata_key(lookup) else {\n";
    out << "            return Ok(None);\n";
    out << "        };\n";
    out << "        let existing = tx.get(&lookup.metadata_entity, &key)?;\n";
    out << "        if existing.is_none() {\n";
    out << "            return Ok(None);\n";
    out << "        }\n";
    out << "        assert_external_system_metadata_expected_version(&existing, "
           "expected_version)?;\n";
    out << "        let mut values = match existing.as_ref().map(|record| &record.document) {\n";
    out << "            Some(Json::Object(values)) => values.clone(),\n";
    out << "            _ => BTreeMap::new(),\n";
    out << "        };\n";
    out << "        for key_value in &lookup.key_values {\n";
    out << "            values.insert(key_value.field.clone(), key_value.value.clone());\n";
    out << "        }\n";
    out << "        values.insert(\"status\".to_string(), Json::String(status.to_string()));\n";
    out << "        tx.put(&lookup.metadata_entity, &key, Json::Object(values))?;\n";
    out << "        tx.get(&lookup.metadata_entity, &key)\n";
    out << "    }\n";
    out << "}\n\n";
    out << "impl<B: Backend> ExternalSystemMetadataResolver<B> for "
           "DefaultExternalSystemOperatorMetadataRepository {\n";
    out << "    fn resolve_metadata(\n";
    out << "        &self,\n";
    out << "        backend: &B,\n";
    out << "        lookup: &ExternalSystemMetadataLookup,\n";
    out << "    ) -> BackendResult<Option<ExternalSystemMetadataResolution>> {\n";
    out << "        let mut tx = backend.begin()?;\n";
    out << "        let resolved = <Self as ExternalSystemMetadataResolver<B>>::"
           "resolve_metadata_tx(self, &mut tx, lookup)?;\n";
    out << "        backend.commit(tx)?;\n";
    out << "        Ok(resolved)\n";
    out << "    }\n\n";
    out << "    fn resolve_metadata_tx(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        lookup: &ExternalSystemMetadataLookup,\n";
    out << "    ) -> BackendResult<Option<ExternalSystemMetadataResolution>> {\n";
    out << "        let record = <Self as "
           "ExternalSystemOperatorMetadataRepository<B>>::get_metadata_tx(\n";
    out << "            self,\n";
    out << "            tx,\n";
    out << "            &ExternalSystemOperatorMetadataGetRequest { lookup: lookup.clone() },\n";
    out << "        )?;\n";
    out << "        Ok(record.map(|record| ExternalSystemMetadataResolution {\n";
    out << "            missing_required_fields: crate::external_system::"
           "missing_required_metadata_fields(&record.document, &lookup.required_fields),\n";
    out << "            record,\n";
    out << "        }))\n";
    out << "    }\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ExternalSystemDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub properties: Vec<ExternalSystemPropertyDescriptor>,\n";
    out << "    pub metadata: Option<ExternalSystemMetadataDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ApiDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub method: Option<String>,\n";
    out << "    pub path: Option<String>,\n";
    out << "    pub input: Option<String>,\n";
    out << "    pub output: Option<String>,\n";
    out << "    pub error: Option<String>,\n";
    out << "    pub starts_workflow: Option<String>,\n";
    out << "    pub enqueues: Option<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ApiServerDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub serves: Vec<String>,\n";
    out << "    pub concurrency: i32,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ApiRouteDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub server_name: String,\n";
    out << "    pub api_name: String,\n";
    out << "    pub method: Option<String>,\n";
    out << "    pub path: Option<String>,\n";
    out << "    pub input: Option<String>,\n";
    out << "    pub output: Option<String>,\n";
    out << "    pub error: Option<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ApiRequestContext {\n";
    out << "    pub server_name: String,\n";
    out << "    pub api_name: String,\n";
    out << "    pub method: Option<String>,\n";
    out << "    pub path: Option<String>,\n";
    out << "    pub body: Json,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ApiResponse {\n";
    out << "    pub status_code: i32,\n";
    out << "    pub body: Json,\n";
    out << "}\n\n";
    out << "pub trait ExternalSystemOperatorMetadataApiHandler<B: Backend> {\n";
    out << "    fn handle_upsert_metadata_tx<R: ExternalSystemOperatorMetadataRepository<B>>(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        repository: &R,\n";
    out << "        request: &ExternalSystemOperatorMetadataUpsertRequest,\n";
    out << "    ) -> BackendResult<ApiResponse>;\n\n";
    out << "    fn handle_get_metadata_tx<R: ExternalSystemOperatorMetadataRepository<B>>(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        repository: &R,\n";
    out << "        request: &ExternalSystemOperatorMetadataGetRequest,\n";
    out << "    ) -> BackendResult<ApiResponse>;\n\n";
    out << "    fn handle_disable_metadata_tx<R: ExternalSystemOperatorMetadataRepository<B>>(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        repository: &R,\n";
    out << "        request: &ExternalSystemOperatorMetadataDisableRequest,\n";
    out << "    ) -> BackendResult<ApiResponse>;\n\n";
    out << "    fn handle_delete_metadata_tx<R: ExternalSystemOperatorMetadataRepository<B>>(\n";
    out << "        &self,\n";
    out << "        tx: &mut B::Tx,\n";
    out << "        repository: &R,\n";
    out << "        request: &ExternalSystemOperatorMetadataDeleteRequest,\n";
    out << "    ) -> BackendResult<ApiResponse>;\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct WorkerDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub singleton: bool,\n";
    out << "    pub lease: Option<String>,\n";
    out << "    pub polls: Option<String>,\n";
    out << "    pub executes: Option<String>,\n";
    out << "    pub concurrency: i32,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct WorkerContext {\n";
    out << "    pub worker_name: String,\n";
    out << "    pub singleton: bool,\n";
    out << "    pub lease: Option<String>,\n";
    out << "    pub polls: Option<String>,\n";
    out << "    pub executes: Option<String>,\n";
    out << "    pub concurrency: i32,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct PolicyRuleDescriptor {\n";
    out << "    pub action: String,\n";
    out << "    pub condition: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct QuotaDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub expression: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct PolicyDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub tenant_scoped_by: Option<String>,\n";
    out << "    pub allows: Vec<PolicyRuleDescriptor>,\n";
    out << "    pub denies: Vec<PolicyRuleDescriptor>,\n";
    out << "    pub quotas: Vec<QuotaDescriptor>,\n";
    out << "    pub audits: Vec<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct ShapeDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub fields: Vec<FieldDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct LogDefinition {\n";
    out << "    pub name: String,\n";
    out << "    pub level: String,\n";
    out << "    pub event_name: String,\n";
    out << "    pub fields: Vec<FieldDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct MetricDefinition {\n";
    out << "    pub name: String,\n";
    out << "    pub kind: String,\n";
    out << "    pub backend_name: String,\n";
    out << "    pub unit: String,\n";
    out << "    pub labels: Vec<FieldDescriptor>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct GarbageCollectionPolicy {\n";
    out << "    pub after: String,\n";
    out << "    pub mode: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EntityStateDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub terminal: bool,\n";
    out << "    pub garbage_collection: Option<GarbageCollectionPolicy>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EntityOwnershipDescriptor {\n";
    out << "    pub authority: String,\n";
    out << "    pub system_of_record: String,\n";
    out << "    pub lifecycle: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EntityRelationDescriptor {\n";
    out << "    pub kind: String,\n";
    out << "    pub name: String,\n";
    out << "    pub target: String,\n";
    out << "    pub optional: bool,\n";
    out << "    pub relation_kind: Option<String>,\n";
    out << "    pub on_parent_delete: Option<String>,\n";
    out << "    pub parent_must_be_in: Vec<String>,\n";
    out << "    pub unique_within_parent: Vec<String>,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EntityChildDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub target_entity: String,\n";
    out << "    pub relation: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EntityInvariantDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub expression: String,\n";
    out << "}\n\n";
    out << "#[derive(Debug, Clone)]\n";
    out << "pub struct EntityDescriptor {\n";
    out << "    pub name: String,\n";
    out << "    pub key_fields: Vec<String>,\n";
    out << "    pub ownership: Option<EntityOwnershipDescriptor>,\n";
    out << "    pub relations: Vec<EntityRelationDescriptor>,\n";
    out << "    pub children: Vec<EntityChildDescriptor>,\n";
    out << "    pub invariants: Vec<EntityInvariantDescriptor>,\n";
    out << "    pub states: Vec<EntityStateDescriptor>,\n";
    out << "    pub initial_state: Option<String>,\n";
    out << "    pub terminal_states: Vec<String>,\n";
    out << "}\n\n";

    return out.str();
}

} // namespace statespec
