#include "statespec/generator.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>
#include <unordered_set>

namespace statespec
{

namespace
{

std::string join_path(const std::string& left, const std::string& right)
{
    if (left.empty())
    {
        return right;
    }
    return left.back() == '/' ? left + right : left + "/" + right;
}

std::string output_root(const GenerateDecl& declaration, const GenerationOptions& options)
{
    if (options.out_override.has_value())
    {
        return *options.out_override;
    }
    if (declaration.out.has_value())
    {
        return *declaration.out;
    }
    return "generated/" + declaration.target;
}

std::string bool_text(bool value)
{
    return value ? "true" : "false";
}

std::string optional_or_empty(const std::optional<std::string>& value)
{
    return value.value_or("");
}

std::string optional_bool_or_empty(const std::optional<bool>& value)
{
    return value.has_value() ? bool_text(*value) : "";
}

bool is_optional_type(const std::string& type)
{
    return !type.empty() && type.back() == '?';
}

std::string strip_optional_suffix(const std::string& type)
{
    return is_optional_type(type) ? type.substr(0, type.size() - 1) : type;
}

std::string to_lower(std::string value)
{
    std::transform(
        value.begin(), value.end(), value.begin(),
        [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); }
    );
    return value;
}

std::string cpp_type_for_statespec_type(const std::string& type)
{
    const auto optional = is_optional_type(type);
    const auto base = strip_optional_suffix(type);

    std::string cpp_type;
    if (base == "string" || base == "uuid" || base == "json")
    {
        cpp_type = "std::string";
    }
    else if (base == "bool")
    {
        cpp_type = "bool";
    }
    else if (base == "int" || base == "int32")
    {
        cpp_type = "std::int32_t";
    }
    else if (base == "int64" || base == "long")
    {
        cpp_type = "std::int64_t";
    }
    else if (base == "double" || base == "decimal")
    {
        cpp_type = "double";
    }
    else if (base == "timestamp")
    {
        cpp_type = "std::chrono::system_clock::time_point";
    }
    else if (base == "duration")
    {
        cpp_type = "std::chrono::seconds";
    }
    else
    {
        cpp_type = base;
    }

    return optional ? "std::optional<" + cpp_type + ">" : cpp_type;
}

std::string payload_struct_name(const QueueDecl& queue, const MessageDecl& message)
{
    return queue.name + message.name + "Payload";
}

void append_header(std::ostringstream& out, const SystemDecl& system, const std::string& target)
{
    out << "# Generated by StateSpec\n";
    out << "# target: " << target << "\n";
    out << "# system: " << system.name << "\n\n";
}

std::string generate_mt_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "entities:\n";
    for (const auto& entity : system.entities)
    {
        out << "  - name: " << entity.name << "\n";
        out << "    keys:\n";
        for (const auto& key : entity.key_fields)
        {
            out << "      - " << key << "\n";
        }
        out << "    fields:\n";
        for (const auto& field : entity.fields)
        {
            out << "      - name: " << field.name << "\n";
            out << "        type: " << field.type << "\n";
            out << "        cpp_type: " << cpp_type_for_statespec_type(field.type) << "\n";
            out << "        optional: " << bool_text(is_optional_type(field.type)) << "\n";
        }
    }
    return out.str();
}

std::string generate_mt_entities_header(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#pragma once\n\n";
    out << "#include <chrono>\n#include <cstddef>\n#include <cstdint>\n#include <optional>\n#include <string>\n#include <string_view>\n\n";
    out << "namespace statespec_generated::mt\n{\n\n";
    out << "struct FieldMetadata\n{\n    std::string_view name;\n    std::string_view statespec_type;\n    std::string_view cpp_type;\n    bool optional;\n};\n\n";
    out << "struct EntityMetadata\n{\n    std::string_view name;\n    const FieldMetadata* fields;\n    std::size_t field_count;\n    const std::string_view* keys;\n    std::size_t key_count;\n};\n\n";

    for (const auto& entity : system.entities)
    {
        out << "struct " << entity.name << "\n{\n";
        for (const auto& field : entity.fields)
        {
            out << "    " << cpp_type_for_statespec_type(field.type) << ' ' << field.name << "{};\n";
        }
        out << "};\n\n";
    }

    out << "const EntityMetadata* entities();\nstd::size_t entity_count();\n\n";
    out << "} // namespace statespec_generated::mt\n";
    return out.str();
}

std::string generate_mt_metadata_source(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#include \"mt_entities.hpp\"\n\n#include <array>\n\n";
    out << "namespace statespec_generated::mt\n{\nnamespace\n{\n\n";
    for (const auto& entity : system.entities)
    {
        const auto symbol = to_lower(entity.name);
        out << "constexpr std::array<FieldMetadata, " << entity.fields.size() << "> " << symbol << "_fields{{\n";
        for (const auto& field : entity.fields)
        {
            out << "    FieldMetadata{\"" << field.name << "\", \"" << field.type << "\", \"" << cpp_type_for_statespec_type(field.type) << "\", " << bool_text(is_optional_type(field.type)) << "},\n";
        }
        out << "}};\n\n";
        out << "constexpr std::array<std::string_view, " << entity.key_fields.size() << "> " << symbol << "_keys{{\n";
        for (const auto& key : entity.key_fields)
        {
            out << "    \"" << key << "\",\n";
        }
        out << "}};\n\n";
    }
    out << "constexpr std::array<EntityMetadata, " << system.entities.size() << "> all_entities{{\n";
    for (const auto& entity : system.entities)
    {
        const auto symbol = to_lower(entity.name);
        out << "    EntityMetadata{\"" << entity.name << "\", " << symbol << "_fields.data(), " << symbol << "_fields.size(), " << symbol << "_keys.data(), " << symbol << "_keys.size()},\n";
    }
    out << "}};\n\n} // namespace\n\n";
    out << "const EntityMetadata* entities()\n{\n    return all_entities.data();\n}\n\n";
    out << "std::size_t entity_count()\n{\n    return all_entities.size();\n}\n\n";
    out << "} // namespace statespec_generated::mt\n";
    return out.str();
}

std::string generate_mt_state_machine_manifest(const SystemDecl& system)
{
    std::ostringstream out;
    append_header(out, system, "mt-state-machines");
    out << "state_machines:\n";
    for (const auto& entity : system.entities)
    {
        if (!entity.state_machine.has_value())
        {
            continue;
        }
        out << "  - entity: " << entity.name << "\n";
        out << "    initial: " << optional_or_empty(entity.state_machine->initial_state) << "\n";
        out << "    states:\n";
        for (const auto& state : entity.state_machine->states)
        {
            out << "      - " << state.name << "\n";
        }
        out << "    terminal_states:\n";
        for (const auto& state : entity.state_machine->terminal_states)
        {
            out << "      - " << state << "\n";
        }
        out << "    transitions:\n";
        for (const auto& transition : entity.state_machine->transitions)
        {
            out << "      - from: " << transition.from << "\n        to: " << transition.to << "\n";
        }
    }
    return out.str();
}

std::string generate_dl_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "leases:\n";
    for (const auto& lease : system.leases)
    {
        out << "  - name: " << lease.name << "\n    resource: " << optional_or_empty(lease.resource) << "\n    ttl: " << optional_or_empty(lease.ttl) << "\n    renew_every: " << optional_or_empty(lease.renew_every) << "\n    holder: " << optional_or_empty(lease.holder) << "\n    fencing_token: " << optional_bool_or_empty(lease.fencing_token) << "\n    max_ttl: " << optional_or_empty(lease.max_ttl) << "\n";
    }
    out << "workers:\n";
    for (const auto& worker : system.workers)
    {
        out << "  - name: " << worker.name << "\n    lease: " << optional_or_empty(worker.lease) << "\n    singleton: " << optional_bool_or_empty(worker.singleton) << "\n    concurrency: " << worker.concurrency.value_or(0) << "\n";
    }
    return out.str();
}

std::string generate_dl_leases_header()
{
    std::ostringstream out;
    out << "#pragma once\n\n#include <cstddef>\n#include <string_view>\n\nnamespace statespec_generated::dl\n{\n\n";
    out << "struct LeaseMetadata\n{\n    std::string_view name;\n    std::string_view resource;\n    std::string_view ttl;\n    std::string_view renew_every;\n    std::string_view holder;\n    bool fencing_token;\n    std::string_view max_ttl;\n};\n\n";
    out << "struct WorkerLeaseBinding\n{\n    std::string_view worker_name;\n    std::string_view lease_name;\n    bool singleton;\n    int concurrency;\n};\n\n";
    out << "const LeaseMetadata* leases();\nstd::size_t lease_count();\nconst WorkerLeaseBinding* worker_lease_bindings();\nstd::size_t worker_lease_binding_count();\nconst LeaseMetadata* find_lease(std::string_view name);\n\n";
    out << "} // namespace statespec_generated::dl\n";
    return out.str();
}

std::string generate_dl_metadata_source(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#include \"dl_leases.hpp\"\n\n#include <array>\n\nnamespace statespec_generated::dl\n{\nnamespace\n{\n\n";
    out << "constexpr std::array<LeaseMetadata, " << system.leases.size() << "> all_leases{{\n";
    for (const auto& lease : system.leases)
    {
        out << "    LeaseMetadata{\"" << lease.name << "\", \"" << optional_or_empty(lease.resource) << "\", \"" << optional_or_empty(lease.ttl) << "\", \"" << optional_or_empty(lease.renew_every) << "\", \"" << optional_or_empty(lease.holder) << "\", " << bool_text(lease.fencing_token.value_or(false)) << ", \"" << optional_or_empty(lease.max_ttl) << "\"},\n";
    }
    out << "}};\n\nconstexpr std::array<WorkerLeaseBinding, " << system.workers.size() << "> all_worker_lease_bindings{{\n";
    for (const auto& worker : system.workers)
    {
        out << "    WorkerLeaseBinding{\"" << worker.name << "\", \"" << optional_or_empty(worker.lease) << "\", " << bool_text(worker.singleton.value_or(false)) << ", " << worker.concurrency.value_or(0) << "},\n";
    }
    out << "}};\n\n} // namespace\n\n";
    out << "const LeaseMetadata* leases()\n{\n    return all_leases.data();\n}\n\nstd::size_t lease_count()\n{\n    return all_leases.size();\n}\n\nconst WorkerLeaseBinding* worker_lease_bindings()\n{\n    return all_worker_lease_bindings.data();\n}\n\nstd::size_t worker_lease_binding_count()\n{\n    return all_worker_lease_bindings.size();\n}\n\nconst LeaseMetadata* find_lease(std::string_view name)\n{\n    for (std::size_t i = 0; i < all_leases.size(); ++i)\n    {\n        if (all_leases[i].name == name)\n        {\n            return &all_leases[i];\n        }\n    }\n    return nullptr;\n}\n\n";
    out << "} // namespace statespec_generated::dl\n";
    return out.str();
}

std::string generate_qu_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "queues:\n";
    for (const auto& queue : system.queues)
    {
        out << "  - name: " << queue.name << "\n    namespace: " << optional_or_empty(queue.namespace_name) << "\n    channel: " << optional_or_empty(queue.channel) << "\n    visibility_timeout: " << optional_or_empty(queue.visibility_timeout) << "\n    max_attempts: " << queue.max_attempts.value_or(0) << "\n    messages:\n";
        for (const auto& message : queue.messages)
        {
            out << "      - name: " << message.name << "\n        payload_struct: " << payload_struct_name(queue, message) << "\n        idempotency_key: " << optional_or_empty(message.idempotency_key) << "\n        payload_fields:\n";
            for (const auto& field : message.payload_fields)
            {
                out << "          - name: " << field.name << "\n            type: " << field.type << "\n            cpp_type: " << cpp_type_for_statespec_type(field.type) << "\n            optional: " << bool_text(is_optional_type(field.type)) << "\n";
            }
        }
    }
    return out.str();
}

std::string generate_qu_messages_header(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#pragma once\n\n#include <chrono>\n#include <cstddef>\n#include <cstdint>\n#include <optional>\n#include <string>\n#include <string_view>\n\nnamespace statespec_generated::qu\n{\n\n";
    out << "struct PayloadFieldMetadata\n{\n    std::string_view name;\n    std::string_view statespec_type;\n    std::string_view cpp_type;\n    bool optional;\n};\n\n";
    out << "struct MessageMetadata\n{\n    std::string_view queue_name;\n    std::string_view message_name;\n    std::string_view payload_struct;\n    std::string_view idempotency_key;\n    const PayloadFieldMetadata* payload_fields;\n    std::size_t payload_field_count;\n};\n\n";
    out << "struct QueueMetadata\n{\n    std::string_view name;\n    std::string_view namespace_name;\n    std::string_view channel;\n    std::string_view visibility_timeout;\n    int max_attempts;\n    const MessageMetadata* messages;\n    std::size_t message_count;\n};\n\n";
    for (const auto& queue : system.queues)
    {
        for (const auto& message : queue.messages)
        {
            out << "struct " << payload_struct_name(queue, message) << "\n{\n";
            for (const auto& field : message.payload_fields)
            {
                out << "    " << cpp_type_for_statespec_type(field.type) << ' ' << field.name << "{};\n";
            }
            out << "};\n\n";
        }
    }
    out << "const QueueMetadata* queues();\nstd::size_t queue_count();\nconst MessageMetadata* messages();\nstd::size_t message_count();\nstd::string_view idempotency_key_field(std::string_view queue_name, std::string_view message_name);\n\n";
    out << "} // namespace statespec_generated::qu\n";
    return out.str();
}

std::string generate_qu_metadata_source(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#include \"qu_messages.hpp\"\n\n#include <array>\n\nnamespace statespec_generated::qu\n{\nnamespace\n{\n\n";
    std::size_t total_messages = 0;
    for (const auto& queue : system.queues)
    {
        total_messages += queue.messages.size();
        for (const auto& message : queue.messages)
        {
            const auto symbol = to_lower(queue.name + message.name);
            out << "constexpr std::array<PayloadFieldMetadata, " << message.payload_fields.size() << "> " << symbol << "_payload_fields{{\n";
            for (const auto& field : message.payload_fields)
            {
                out << "    PayloadFieldMetadata{\"" << field.name << "\", \"" << field.type << "\", \"" << cpp_type_for_statespec_type(field.type) << "\", " << bool_text(is_optional_type(field.type)) << "},\n";
            }
            out << "}};\n\n";
        }
    }
    out << "constexpr std::array<MessageMetadata, " << total_messages << "> all_messages{{\n";
    for (const auto& queue : system.queues)
    {
        for (const auto& message : queue.messages)
        {
            const auto symbol = to_lower(queue.name + message.name);
            out << "    MessageMetadata{\"" << queue.name << "\", \"" << message.name << "\", \"" << payload_struct_name(queue, message) << "\", \"" << optional_or_empty(message.idempotency_key) << "\", " << symbol << "_payload_fields.data(), " << symbol << "_payload_fields.size()},\n";
        }
    }
    out << "}};\n\n";
    for (const auto& queue : system.queues)
    {
        const auto symbol = to_lower(queue.name);
        out << "constexpr std::array<MessageMetadata, " << queue.messages.size() << "> " << symbol << "_messages{{\n";
        for (const auto& message : queue.messages)
        {
            const auto message_symbol = to_lower(queue.name + message.name);
            out << "    MessageMetadata{\"" << queue.name << "\", \"" << message.name << "\", \"" << payload_struct_name(queue, message) << "\", \"" << optional_or_empty(message.idempotency_key) << "\", " << message_symbol << "_payload_fields.data(), " << message_symbol << "_payload_fields.size()},\n";
        }
        out << "}};\n\n";
    }
    out << "constexpr std::array<QueueMetadata, " << system.queues.size() << "> all_queues{{\n";
    for (const auto& queue : system.queues)
    {
        const auto symbol = to_lower(queue.name);
        out << "    QueueMetadata{\"" << queue.name << "\", \"" << optional_or_empty(queue.namespace_name) << "\", \"" << optional_or_empty(queue.channel) << "\", \"" << optional_or_empty(queue.visibility_timeout) << "\", " << queue.max_attempts.value_or(0) << ", " << symbol << "_messages.data(), " << symbol << "_messages.size()},\n";
    }
    out << "}};\n\n} // namespace\n\n";
    out << "const QueueMetadata* queues()\n{\n    return all_queues.data();\n}\n\nstd::size_t queue_count()\n{\n    return all_queues.size();\n}\n\nconst MessageMetadata* messages()\n{\n    return all_messages.data();\n}\n\nstd::size_t message_count()\n{\n    return all_messages.size();\n}\n\nstd::string_view idempotency_key_field(std::string_view queue_name, std::string_view message_name)\n{\n    for (std::size_t i = 0; i < all_messages.size(); ++i)\n    {\n        const auto& message = all_messages[i];\n        if (message.queue_name == queue_name && message.message_name == message_name)\n        {\n            return message.idempotency_key;\n        }\n    }\n    return {};\n}\n\n";
    out << "} // namespace statespec_generated::qu\n";
    return out.str();
}

std::string generate_wf_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "workflows:\n";
    for (const auto& workflow : system.workflows)
    {
        out << "  - name: " << workflow.name << "\n    version: " << workflow.version.value_or(0) << "\n    singleton: " << optional_bool_or_empty(workflow.singleton) << "\n    expected_execution_time: " << optional_or_empty(workflow.expected_execution_time) << "\n    start: " << optional_or_empty(workflow.start_step) << "\n    steps:\n";
        for (const auto& step : workflow.steps)
        {
            out << "      - name: " << step.name << "\n        expected_execution_time: " << optional_or_empty(step.expected_execution_time) << "\n        max_retries: " << step.max_retries.value_or(0) << "\n";
        }
    }
    return out.str();
}

std::string generate_wf_workflows_header()
{
    std::ostringstream out;
    out << "#pragma once\n\n#include <cstddef>\n#include <string_view>\n\nnamespace statespec_generated::wf\n{\n\n";
    out << "struct WorkflowStepMetadata\n{\n    std::string_view name;\n    std::string_view expected_execution_time;\n    int max_retries;\n};\n\n";
    out << "struct WorkflowMetadata\n{\n    std::string_view name;\n    int version;\n    bool singleton;\n    std::string_view expected_execution_time;\n    std::string_view start_step;\n    const WorkflowStepMetadata* steps;\n    std::size_t step_count;\n};\n\n";
    out << "const WorkflowMetadata* workflows();\nstd::size_t workflow_count();\nconst WorkflowMetadata* find_workflow(std::string_view name);\nconst WorkflowStepMetadata* find_step(std::string_view workflow_name, std::string_view step_name);\nstd::string_view start_step(std::string_view workflow_name);\n\n";
    out << "} // namespace statespec_generated::wf\n";
    return out.str();
}

std::string generate_wf_metadata_source(const SystemDecl& system)
{
    std::ostringstream out;
    out << "#include \"wf_workflows.hpp\"\n\n#include <array>\n\nnamespace statespec_generated::wf\n{\nnamespace\n{\n\n";
    for (const auto& workflow : system.workflows)
    {
        const auto symbol = to_lower(workflow.name);
        out << "constexpr std::array<WorkflowStepMetadata, " << workflow.steps.size() << "> " << symbol << "_steps{{\n";
        for (const auto& step : workflow.steps)
        {
            out << "    WorkflowStepMetadata{\"" << step.name << "\", \"" << optional_or_empty(step.expected_execution_time) << "\", " << step.max_retries.value_or(0) << "},\n";
        }
        out << "}};\n\n";
    }
    out << "constexpr std::array<WorkflowMetadata, " << system.workflows.size() << "> all_workflows{{\n";
    for (const auto& workflow : system.workflows)
    {
        const auto symbol = to_lower(workflow.name);
        out << "    WorkflowMetadata{\"" << workflow.name << "\", " << workflow.version.value_or(0) << ", " << bool_text(workflow.singleton.value_or(false)) << ", \"" << optional_or_empty(workflow.expected_execution_time) << "\", \"" << optional_or_empty(workflow.start_step) << "\", " << symbol << "_steps.data(), " << symbol << "_steps.size()},\n";
    }
    out << "}};\n\n} // namespace\n\n";
    out << "const WorkflowMetadata* workflows()\n{\n    return all_workflows.data();\n}\n\nstd::size_t workflow_count()\n{\n    return all_workflows.size();\n}\n\nconst WorkflowMetadata* find_workflow(std::string_view name)\n{\n    for (std::size_t i = 0; i < all_workflows.size(); ++i)\n    {\n        if (all_workflows[i].name == name)\n        {\n            return &all_workflows[i];\n        }\n    }\n    return nullptr;\n}\n\nconst WorkflowStepMetadata* find_step(std::string_view workflow_name, std::string_view step_name)\n{\n    const auto* workflow = find_workflow(workflow_name);\n    if (workflow == nullptr)\n    {\n        return nullptr;\n    }\n    for (std::size_t i = 0; i < workflow->step_count; ++i)\n    {\n        if (workflow->steps[i].name == step_name)\n        {\n            return &workflow->steps[i];\n        }\n    }\n    return nullptr;\n}\n\nstd::string_view start_step(std::string_view workflow_name)\n{\n    const auto* workflow = find_workflow(workflow_name);\n    return workflow == nullptr ? std::string_view{} : workflow->start_step;\n}\n\n";
    out << "} // namespace statespec_generated::wf\n";
    return out.str();
}

std::string generate_openapi_stub(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    out << "openapi: 3.1.0\ninfo:\n  title: " << system.name << " API\n  version: 0.1.0\npaths:\n";
    for (const auto& api : system.apis)
    {
        out << "  \"" << api.path.value_or("/") << "\":\n    " << api.method.value_or("GET") << ":\n      operationId: " << api.name << "\n      responses:\n        \"200\":\n          description: generated stub\n";
    }
    (void)declaration;
    return out.str();
}

std::string manifest_name_for_target(const std::string& target)
{
    return target == "openapi" ? "openapi.yaml" : target + "-manifest.yaml";
}

std::string content_for_target(const SystemDecl& system, const GenerateDecl& declaration)
{
    if (declaration.target == "openapi")
    {
        return generate_openapi_stub(system, declaration);
    }
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "status: scaffold-only\n";
    return out.str();
}

std::vector<GenerateDecl> selected_declarations(const SystemDecl& system, const GenerationOptions& options)
{
    std::vector<GenerateDecl> selected;
    for (const auto& declaration : system.generators)
    {
        if (!options.target_override.has_value() || declaration.target == *options.target_override)
        {
            selected.push_back(declaration);
        }
    }
    if (selected.empty() && options.target_override.has_value())
    {
        GenerateDecl declaration;
        declaration.target = *options.target_override;
        selected.push_back(declaration);
    }
    return selected;
}

} // namespace

GenerationResult Generator::generate(const Spec& spec, const GenerationOptions& options, DiagnosticBag& diagnostics) const
{
    GenerationResult result;
    if (!spec.system.has_value())
    {
        diagnostics.error(SourceRange{}, "SSPEC5001", "generation requires a system declaration");
        return result;
    }
    const auto& system = *spec.system;
    const auto declarations = selected_declarations(system, options);
    if (declarations.empty())
    {
        diagnostics.error(system.range, "SSPEC5002", "generation requires at least one generate declaration");
        return result;
    }
    for (const auto& declaration : declarations)
    {
        generate_target(system, declaration, options, result, diagnostics);
    }
    return result;
}

void Generator::generate_target(const SystemDecl& system, const GenerateDecl& declaration, const GenerationOptions& options, GenerationResult& result, DiagnosticBag& diagnostics) const
{
    static const std::unordered_set<std::string> supported_targets{
        "mt", "dl", "qu", "wf", "openapi", "proto", "docs", "tests",
    };
    if (declaration.target == "all")
    {
        for (const auto& target : {"mt", "dl", "qu", "wf", "openapi"})
        {
            GenerateDecl expanded = declaration;
            expanded.target = target;
            generate_target(system, expanded, options, result, diagnostics);
        }
        return;
    }
    if (supported_targets.find(declaration.target) == supported_targets.end())
    {
        diagnostics.error(declaration.range, "SSPEC5003", "unsupported generate target '" + declaration.target + "'");
        return;
    }
    const auto root = output_root(declaration, options);
    if (declaration.target == "mt")
    {
        result.files.push_back(GeneratedFile{join_path(root, "mt-manifest.yaml"), generate_mt_manifest(system, declaration)});
        result.files.push_back(GeneratedFile{join_path(root, "mt_entities.hpp"), generate_mt_entities_header(system)});
        result.files.push_back(GeneratedFile{join_path(root, "mt_metadata.cpp"), generate_mt_metadata_source(system)});
        result.files.push_back(GeneratedFile{join_path(root, "mt-state-machines.yaml"), generate_mt_state_machine_manifest(system)});
        return;
    }
    if (declaration.target == "dl")
    {
        result.files.push_back(GeneratedFile{join_path(root, "dl-manifest.yaml"), generate_dl_manifest(system, declaration)});
        result.files.push_back(GeneratedFile{join_path(root, "dl_leases.hpp"), generate_dl_leases_header()});
        result.files.push_back(GeneratedFile{join_path(root, "dl_metadata.cpp"), generate_dl_metadata_source(system)});
        return;
    }
    if (declaration.target == "qu")
    {
        result.files.push_back(GeneratedFile{join_path(root, "qu-manifest.yaml"), generate_qu_manifest(system, declaration)});
        result.files.push_back(GeneratedFile{join_path(root, "qu_messages.hpp"), generate_qu_messages_header(system)});
        result.files.push_back(GeneratedFile{join_path(root, "qu_metadata.cpp"), generate_qu_metadata_source(system)});
        return;
    }
    if (declaration.target == "wf")
    {
        result.files.push_back(GeneratedFile{join_path(root, "wf-manifest.yaml"), generate_wf_manifest(system, declaration)});
        result.files.push_back(GeneratedFile{join_path(root, "wf_workflows.hpp"), generate_wf_workflows_header()});
        result.files.push_back(GeneratedFile{join_path(root, "wf_metadata.cpp"), generate_wf_metadata_source(system)});
        return;
    }
    result.files.push_back(GeneratedFile{join_path(root, manifest_name_for_target(declaration.target)), content_for_target(system, declaration)});
}

} // namespace statespec
