#include "statespec/generator.hpp"

#include <sstream>
#include <unordered_set>

namespace statespec
{

namespace
{

std::string default_out_for_target(const std::string& target)
{
    return "generated/" + target;
}

std::string output_root(
    const GenerateDecl& declaration,
    const GenerationOptions& options
)
{
    if (options.out_override.has_value())
    {
        return *options.out_override;
    }
    if (declaration.out.has_value())
    {
        return *declaration.out;
    }
    return default_out_for_target(declaration.target);
}

std::string join_path(
    const std::string& left,
    const std::string& right
)
{
    if (left.empty())
    {
        return right;
    }
    if (left.back() == '/')
    {
        return left + right;
    }
    return left + "/" + right;
}

std::string bool_text(bool value)
{
    return value ? "true" : "false";
}

std::string optional_or_empty(const std::optional<std::string>& value)
{
    return value.value_or("");
}

void append_header(
    std::ostringstream& out,
    const SystemDecl& system,
    const std::string& target
)
{
    out << "# Generated by StateSpec\n";
    out << "# target: " << target << "\n";
    out << "# system: " << system.name << "\n\n";
}

std::string generate_mt_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "entities:\n";
    for (const auto& entity : system.entities)
    {
        out << "  - name: " << entity.name << "\n";
        out << "    keys:\n";
        for (const auto& key : entity.key_fields)
        {
            out << "      - " << key << "\n";
        }
        out << "    fields:\n";
        for (const auto& field : entity.fields)
        {
            out << "      - name: " << field.name << "\n";
            out << "        type: " << field.type << "\n";
        }
    }
    return out.str();
}

std::string generate_dl_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "leases:\n";
    for (const auto& lease : system.leases)
    {
        out << "  - name: " << lease.name << "\n";
        out << "    resource: " << optional_or_empty(lease.resource) << "\n";
        out << "    ttl: " << optional_or_empty(lease.ttl) << "\n";
        out << "    renew_every: " << optional_or_empty(lease.renew_every) << "\n";
        out << "    holder: " << optional_or_empty(lease.holder) << "\n";
        out << "    fencing_token: " << (lease.fencing_token.has_value() ? bool_text(*lease.fencing_token) : "") << "\n";
    }
    out << "workers:\n";
    for (const auto& worker : system.workers)
    {
        out << "  - name: " << worker.name << "\n";
        out << "    lease: " << optional_or_empty(worker.lease) << "\n";
        out << "    singleton: " << (worker.singleton.has_value() ? bool_text(*worker.singleton) : "") << "\n";
    }
    return out.str();
}

std::string generate_qu_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "queues:\n";
    for (const auto& queue : system.queues)
    {
        out << "  - name: " << queue.name << "\n";
        out << "    namespace: " << optional_or_empty(queue.namespace_name) << "\n";
        out << "    channel: " << optional_or_empty(queue.channel) << "\n";
        out << "    messages:\n";
        for (const auto& message : queue.messages)
        {
            out << "      - name: " << message.name << "\n";
            out << "        idempotency_key: " << optional_or_empty(message.idempotency_key) << "\n";
        }
    }
    return out.str();
}

std::string generate_wf_manifest(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "workflows:\n";
    for (const auto& workflow : system.workflows)
    {
        out << "  - name: " << workflow.name << "\n";
        out << "    version: " << workflow.version.value_or(0) << "\n";
        out << "    start: " << optional_or_empty(workflow.start_step) << "\n";
        out << "    steps:\n";
        for (const auto& step : workflow.steps)
        {
            out << "      - name: " << step.name << "\n";
            out << "        expected_execution_time: " << optional_or_empty(step.expected_execution_time) << "\n";
            out << "        max_retries: " << step.max_retries.value_or(0) << "\n";
        }
    }
    return out.str();
}

std::string generate_openapi_stub(const SystemDecl& system, const GenerateDecl& declaration)
{
    std::ostringstream out;
    out << "openapi: 3.1.0\n";
    out << "info:\n";
    out << "  title: " << system.name << " API\n";
    out << "  version: 0.1.0\n";
    out << "paths:\n";
    for (const auto& api : system.apis)
    {
        const auto path = api.path.value_or("/");
        const auto method = api.method.value_or("GET");
        out << "  \"" << path << "\":\n";
        out << "    " << method << ":\n";
        out << "      operationId: " << api.name << "\n";
        out << "      responses:\n";
        out << "        \"200\":\n";
        out << "          description: generated stub\n";
    }
    (void)declaration;
    return out.str();
}

std::string manifest_name_for_target(const std::string& target)
{
    if (target == "openapi")
    {
        return "openapi.yaml";
    }
    return target + "-manifest.yaml";
}

std::string content_for_target(
    const SystemDecl& system,
    const GenerateDecl& declaration
)
{
    if (declaration.target == "mt")
    {
        return generate_mt_manifest(system, declaration);
    }
    if (declaration.target == "dl")
    {
        return generate_dl_manifest(system, declaration);
    }
    if (declaration.target == "qu")
    {
        return generate_qu_manifest(system, declaration);
    }
    if (declaration.target == "wf")
    {
        return generate_wf_manifest(system, declaration);
    }
    if (declaration.target == "openapi")
    {
        return generate_openapi_stub(system, declaration);
    }

    std::ostringstream out;
    append_header(out, system, declaration.target);
    out << "status: scaffold-only\n";
    return out.str();
}

std::vector<GenerateDecl> selected_declarations(
    const SystemDecl& system,
    const GenerationOptions& options
)
{
    std::vector<GenerateDecl> selected;
    for (const auto& declaration : system.generators)
    {
        if (!options.target_override.has_value() || declaration.target == *options.target_override)
        {
            selected.push_back(declaration);
        }
    }

    if (selected.empty() && options.target_override.has_value())
    {
        GenerateDecl declaration;
        declaration.target = *options.target_override;
        selected.push_back(declaration);
    }

    return selected;
}

} // namespace

GenerationResult Generator::generate(
    const Spec& spec,
    const GenerationOptions& options,
    DiagnosticBag& diagnostics
) const
{
    GenerationResult result;
    if (!spec.system.has_value())
    {
        diagnostics.error(SourceRange{}, "SSPEC5001", "generation requires a system declaration");
        return result;
    }

    const auto& system = *spec.system;
    const auto declarations = selected_declarations(system, options);
    if (declarations.empty())
    {
        diagnostics.error(system.range, "SSPEC5002", "generation requires at least one generate declaration");
        return result;
    }

    for (const auto& declaration : declarations)
    {
        generate_target(system, declaration, options, result, diagnostics);
    }

    return result;
}

void Generator::generate_target(
    const SystemDecl& system,
    const GenerateDecl& declaration,
    const GenerationOptions& options,
    GenerationResult& result,
    DiagnosticBag& diagnostics
) const
{
    static const std::unordered_set<std::string> supported_targets{
        "mt", "dl", "qu", "wf", "openapi", "proto", "docs", "tests",
    };

    if (declaration.target == "all")
    {
        for (const auto& target : {"mt", "dl", "qu", "wf", "openapi"})
        {
            GenerateDecl expanded = declaration;
            expanded.target = target;
            generate_target(system, expanded, options, result, diagnostics);
        }
        return;
    }

    if (supported_targets.find(declaration.target) == supported_targets.end())
    {
        diagnostics.error(declaration.range, "SSPEC5003", "unsupported generate target '" + declaration.target + "'");
        return;
    }

    const auto root = output_root(declaration, options);
    const auto path = join_path(root, manifest_name_for_target(declaration.target));
    result.files.push_back(GeneratedFile{path, content_for_target(system, declaration)});
}

} // namespace statespec
